// Auto-generated from rules.py — DO NOT EDIT MANUALLY

export const BURSTINESS_TARGET = 0.7;
export const SYNONYM_RATE = 0.45;
export const PHRASE_RATE = 0.9;
export const RESTRUCTURE_RATE = 0.35;
export const CLAUSE_SWAP_RATE = 0.3;

export const AI_STARTER_REPLACEMENTS: Record<string, string[]> = {
  "furthermore, ": ["In addition, ", "Beyond this, ", "Building on this, ", "Alongside this, "],
  "moreover, ": ["More importantly, ", "Equally significant is the fact that ", "On a related note, ", "What is more, "],
  "additionally, ": ["Also, ", "On top of this, ", "Added to this, ", "Along the same lines, "],
  "consequently, ": ["As a result, ", "This led to ", "The outcome was that ", "Because of this, "],
  "however, ": ["That said, ", "On the other hand, ", "Even so, ", "Yet "],
  "in conclusion, ": ["Ultimately, ", "In the final analysis, ", "Taken together, ", "All things considered, "],
  "in summary, ": ["To sum up, ", "Taken as a whole, ", "On balance, "],
  "therefore, ": ["As such, ", "For this reason, ", "Hence, ", "This means that "],
  "nevertheless, ": ["Even so, ", "Despite this, ", "Notwithstanding this, ", "All the same, "],
  "subsequently, ": ["Following this, ", "After that, ", "In turn, ", "Later on, "],
  "accordingly, ": ["In response, ", "As a result, ", "In line with this, "],
  "notably, ": ["It is worth noting that ", "Of particular interest is that ", "Significantly, "],
  "specifically, ": ["In particular, ", "To be precise, ", "More precisely, "],
  "thus, ": ["As a consequence, ", "For this reason, ", "Hence, "],
  "while ": ["Although ", "Even though ", "Whereas ", "Despite the fact that "],
  "despite these advantages, ": ["Regardless of these merits, ", "Notwithstanding these benefits, ", "Even with these gains, "],
  "despite ": ["In spite of ", "Regardless of ", "Notwithstanding "],
  "as a result, ": ["Because of this, ", "The effect of this was that ", "This brought about a situation where "],
  "for example, ": ["To illustrate, ", "As an example, ", "A case in point is that ", "For instance, "],
  "for instance, ": ["As an illustration, ", "To give an example, ", "Consider the case where "],
  "on the positive side, ": ["Looking at the benefits, ", "Among the advantages, ", "From a positive perspective, "],
  "on the other hand, ": ["Conversely, ", "By contrast, ", "In contrast, ", "At the same time, "],
  "in other words, ": ["Put differently, ", "To rephrase, ", "That is to say, "],
  "it is worth noting that ": ["One key observation is that ", "A notable point is that ", "Attention should be drawn to the fact that "],
  "it is important to note that ": ["One should recognize that ", "A critical observation is that ", "It bears mentioning that "],
  "another important ": ["A further noteworthy ", "An additional key ", "One more notable "],
  "another significant ": ["A further major ", "One more considerable ", "An additional notable "],
  "one of the most significant ": ["Among the most notable ", "Perhaps the most substantial ", "Arguably the most notable "],
  "one of the most important ": ["A key ", "Among the most vital ", "Perhaps the most essential "],
  "this has led to ": ["The consequence has been ", "This has resulted in ", "This has given rise to "],
  "this has resulted in ": ["The outcome has been ", "This has brought about ", "This gave way to "],
  "in addition, ": ["Beyond this, ", "Also, ", "What is more, ", "On top of this, "],
  "overall, ": ["On the whole, ", "Broadly speaking, ", "In general terms, "],
  "to begin with, ": ["First of all, ", "At the outset, ", "To start, "],
  "first and foremost, ": ["Above all, ", "Most importantly, ", "To begin, "],
  "in today's world, ": ["At present, ", "In the current landscape, ", "Nowadays, "],
  "in the modern era, ": ["At present, ", "In contemporary times, ", "Nowadays, "],
  "it is essential to ": ["One must ", "It remains necessary to ", "There is a clear need to "],
  "it is important to ": ["One should ", "It remains necessary to ", "There is value in "],
  "this essay explores ": ["This paper examines ", "The discussion below considers ", "This piece investigates "],
  "this essay examines ": ["This paper analyses ", "This discussion considers ", "The following analysis investigates "],
  "this essay discusses ": ["This paper considers ", "The present discussion addresses ", "This piece looks at "],
  "the purpose of this essay ": ["The aim of this paper ", "The goal of this discussion ", "The objective of this analysis "],
  "in recent years, ": ["Over the past few years, ", "Lately, ", "In the recent period, "],
  "throughout history, ": ["Across the centuries, ", "Over time, ", "Historically, "],
  "there are several ": ["A number of ", "Multiple ", "Various "],
  "there are many ": ["Numerous ", "A wide range of ", "Several "],
  "it can be seen that ": ["Evidently, ", "Observably, ", "One can note that "],
  "it is clear that ": ["Plainly, ", "Evidently, ", "Without question, "],
  "looking at ": ["Examining ", "Considering ", "Reviewing "],
  "when it comes to ": ["Regarding ", "In the matter of ", "With respect to "],
  "when we look at ": ["Upon examining ", "Reviewing ", "Considering "],
  "given that ": ["Since ", "Considering that ", "In view of the fact that "],
  "due to ": ["Owing to ", "Because of ", "As a consequence of "],
};

export const PHRASE_SUBSTITUTIONS: Record<string, string[]> = {
  "refers to the": ["denotes the", "pertains to the", "concerns the", "relates to the"],
  "increasing interconnectedness": ["growing linkages", "rising integration", "deepening connections", "expanding interdependence"],
  "over the past few decades": ["across the last several decades", "throughout the past several decades", "over the last number of decades"],
  "has significantly transformed": ["has profoundly reshaped", "has considerably altered", "has markedly changed", "has deeply influenced"],
  "has also introduced": ["has likewise brought about", "has equally given rise to", "has at the same time created"],
  "the impact of": ["the effect of", "the influence of", "the consequences of"],
  "is complex": ["is multifaceted", "is nuanced", "is far from straightforward"],
  "involving both positive and negative effects": ["encompassing both beneficial and adverse outcomes", "with both favourable and unfavourable dimensions", "spanning both advantageous and detrimental consequences"],
  "both positive and negative": ["both beneficial and adverse", "both favourable and unfavourable", "both advantageous and detrimental"],
  "positive impacts": ["beneficial effects", "favourable outcomes", "constructive results"],
  "negative effects": ["adverse consequences", "detrimental outcomes", "unfavourable results"],
  "economic growth": ["economic expansion", "economic advancement", "economic progress"],
  "increased trade": ["expanded commerce", "greater trade activity", "broader trade flows"],
  "trade opportunities": ["commercial prospects", "opportunities for commerce", "avenues for trade"],
  "have gained access to": ["have been able to enter", "have secured entry into", "now have the ability to participate in"],
  "international markets": ["global markets", "overseas markets", "world markets"],
  "allowing them to": ["enabling them to", "giving them the capacity to", "making it possible for them to"],
  "export goods and services": ["sell products and services abroad", "ship goods and services overseas", "market their products and services internationally"],
  "has led to": ["has brought about", "has resulted in", "has given rise to"],
  "has resulted in": ["has brought about", "has led to", "has triggered", "has given rise to"],
  "has brought about": ["has resulted in", "has led to", "has caused", "has triggered"],
  "has given rise to": ["has led to", "has brought about", "has produced"],
  "job creation": ["employment generation", "the creation of employment", "new employment opportunities"],
  "for example": ["to illustrate", "as an example", "a case in point is", "consider the case of"],
  "for instance": ["as an illustration", "to give an example", "one notable case is"],
  "have experienced rapid": ["have witnessed swift", "have undergone accelerated", "have seen rapid"],
  "economic growth due to": ["economic expansion driven by", "economic advancement fuelled by", "economic progress stemming from"],
  "as a result": ["consequently", "because of this", "this led to the situation where", "the effect was that"],
  "as a result,": ["Consequently,", "Because of this,", "The outcome of this was that", "In response to this,"],
  "has helped many": ["has enabled numerous", "has assisted many", "has allowed several"],
  "another important benefit": ["a further key advantage", "an additional noteworthy gain", "one more notable benefit"],
  "take advantage of": ["capitalise on", "exploit the benefits of", "leverage"],
  "lower labor costs": ["cheaper labour", "reduced workforce expenses", "more affordable manpower"],
  "these investments often lead to": ["such investments frequently result in", "these capital flows often bring about"],
  "the creation of": ["the establishment of", "the building of", "the development of"],
  "employment opportunities": ["job openings", "work prospects", "employment prospects"],
  "in addition": ["moreover", "besides", "what is more"],
  "in addition,": ["Moreover,", "Besides,", "Beyond that,", "What is more,"],
  "essential for": ["critical for", "vital to", "indispensable for"],
  "long-term development": ["sustained progress", "enduring advancement", "lasting growth"],
  "has also contributed to": ["has likewise aided", "has equally supported", "has also played a part in"],
  "poverty reduction": ["the alleviation of poverty", "reducing poverty levels", "the reduction of poverty"],
  "improved standards of living": ["enhanced quality of life", "better living conditions", "raised standards of living"],
  "lifted millions of people out of": ["enabled millions to escape", "raised millions above the threshold of"],
  "extreme poverty": ["deep poverty", "severe destitution", "dire poverty"],
  "small businesses and entrepreneurs": ["small enterprises and business owners", "small-scale firms and entrepreneurs"],
  "expand their operations": ["grow their activities", "broaden their scope", "scale up their ventures"],
  "access to education": ["educational access", "the ability to obtain education", "opportunities for learning"],
  "access to global markets": ["entry to international markets", "reach into the world economy"],
  "despite these advantages": ["notwithstanding these benefits", "regardless of these merits", "even with these gains"],
  "one major concern": ["a key worry", "a primary source of concern", "a leading issue"],
  "economic inequality": ["economic disparity", "income inequality", "wealth gaps"],
  "has created wealth": ["has generated prosperity", "has produced economic value"],
  "has not been evenly distributed": ["has been unequal", "has been spread unevenly", "has not reached all groups equally"],
  "the benefits of": ["the gains from", "the advantages of", "the positive outcomes of"],
  "leaving rural communities": ["while rural populations", "with rural areas", "excluding rural groups"],
  "widening gap between the rich and the poor": ["growing divide between wealthy and disadvantaged groups", "increasing disparity between high-income and low-income populations"],
  "can lead to": ["may give rise to", "could result in", "risks producing"],
  "social unrest": ["social instability", "civil discontent", "public dissatisfaction"],
  "economic instability": ["financial volatility", "economic uncertainty", "economic fragility"],
  "continue to struggle with": ["still face", "remain burdened by", "persistently contend with"],
  "limited access to": ["restricted access to", "inadequate access to", "insufficient availability of"],
  "basic services": ["essential services", "fundamental services", "core services"],
  "another significant drawback": ["a further notable disadvantage", "one more considerable downside", "an additional major limitation"],
  "rely heavily on": ["depend substantially on", "are largely dependent on", "lean heavily upon"],
  "raw materials": ["unprocessed commodities", "primary resources", "natural resources"],
  "this dependence makes them vulnerable to": ["such reliance exposes them to", "this dependency leaves them open to", "this reliance renders them susceptible to"],
  "fluctuations in": ["changes in", "volatility in", "shifts in", "swings in"],
  "global demand": ["international demand", "worldwide demand", "demand across markets"],
  "economic crises": ["economic downturns", "financial difficulties", "periods of economic hardship"],
  "may face": ["could encounter", "risk experiencing", "might confront"],
  "limit domestic control over": ["restrict local authority over", "constrain national sovereignty in"],
  "has also led to": ["has equally resulted in", "has likewise caused", "has in turn produced"],
  "exploitation of labor": ["worker exploitation", "labour abuse", "the mistreatment of workers"],
  "poor working conditions": ["inadequate working environments", "substandard labour conditions", "unsafe workplace environments"],
  "in the pursuit of": ["in an effort to achieve", "in seeking", "while striving for"],
  "lower production costs": ["reduced manufacturing expenses", "cheaper production", "minimised operational costs"],
  "weak labor laws": ["lax employment regulations", "inadequate labour protections", "lenient workplace legislation"],
  "low wages": ["meagre pay", "poor remuneration", "inadequate wages"],
  "long working hours": ["extended work schedules", "excessively lengthy shifts"],
  "unsafe working environments": ["hazardous workplaces", "dangerous working conditions"],
  "has been criticized for": ["has faced criticism over", "has drawn scrutiny for", "has been condemned for"],
  "raising ethical concerns": ["prompting moral questions", "sparking ethical debates", "giving rise to ethical issues"],
  "environmental degradation": ["ecological damage", "harm to the environment", "environmental deterioration"],
  "another critical issue": ["a further pressing concern", "one more serious problem", "an additional key challenge"],
  "associated with": ["linked to", "connected to", "tied to"],
  "industrial activity": ["manufacturing operations", "industrial processes", "productive activity"],
  "resource extraction": ["the harvesting of natural resources", "removal of raw materials", "mining and extraction"],
  "can lead to pollution": ["may cause contamination", "could generate pollution", "risks creating environmental contamination"],
  "deforestation": ["the loss of forests", "forest clearance", "the removal of tree cover"],
  "loss of biodiversity": ["declining biological diversity", "species loss", "the erosion of ecosystems"],
  "economic growth over environmental protection": ["economic advancement at the expense of the environment", "commercial interests above ecological concerns"],
  "long-term environmental damage": ["lasting ecological harm", "enduring environmental degradation"],
  "sustainable development": ["long-term sustainable progress", "environmentally sound growth"],
  "cultural impacts": ["effects on culture", "cultural consequences", "the cultural dimension"],
  "also deserve attention": ["are equally worthy of consideration", "should also be examined", "merit discussion as well"],
  "promotes the spread of": ["accelerates the diffusion of", "facilitates the spread of", "drives the expansion of"],
  "cultural exchange and understanding": ["cross-cultural interaction and awareness", "intercultural dialogue and comprehension"],
  "erosion of local traditions": ["weakening of indigenous practices", "decline of traditional customs", "fading of local cultural heritage"],
  "cultural diversity": ["cultural pluralism", "the variety of cultures", "multicultural richness"],
  "has had a profound": ["has exerted a deep", "has had a far-reaching", "has exercised a sweeping"],
  "multifaceted impact": ["wide-ranging effect", "complex influence", "many-sided consequence"],
  "on the positive side": ["among the benefits", "from a favourable standpoint", "looking at the advantages"],
  "stimulated economic growth": ["spurred economic expansion", "driven economic advancement", "catalysed economic progress"],
  "facilitated technological transfer": ["enabled the movement of technology", "supported the sharing of technical knowledge"],
  "has also generated": ["has equally produced", "has likewise given rise to"],
  "labor exploitation": ["the abuse of workers", "worker mistreatment", "unfair labour practices"],
  "cultural erosion": ["cultural decline", "the weakening of cultural identity", "the loss of cultural heritage"],
  "the overall impact": ["the net effect", "the aggregate outcome", "the cumulative influence"],
  "depends largely on": ["hinges primarily upon", "is largely determined by", "is shaped principally by"],
  "how governments and institutions": ["the manner in which governments and bodies", "the way authorities and organizations"],
  "manage and regulate": ["govern and oversee", "control and direct", "steer and supervise"],
  "to maximize the benefits": ["to capitalise on the gains", "in order to amplify the advantages", "to derive the greatest value"],
  "minimize the drawbacks": ["reduce the downsides", "mitigate the disadvantages", "lessen the negative effects"],
  "must implement policies": ["need to adopt measures", "should put in place regulations", "ought to introduce legislation"],
  "promote inclusive growth": ["foster equitable expansion", "encourage broad-based development", "advance inclusive progress"],
  "protect workers and the environment": ["safeguard labour rights and ecological systems", "shield employees and natural resources"],
  "strengthen domestic industries": ["bolster local industry", "reinforce home-grown sectors", "support national productive capacity"],
  "by doing so": ["in this way", "through such measures", "by taking these steps"],
  "harness globalization as a tool": ["leverage globalisation as an instrument", "use globalisation as a vehicle"],
  "equitable development": ["fair and balanced development", "just growth", "development that benefits all"],
  "it is important to note that": ["it is worth pointing out that", "one key observation is that", "a notable point is that", "an important aspect is that"],
  "it is crucial that": ["it is essential that", "it remains vital that", "it is of great importance that"],
  "it should be noted that": ["it is worth mentioning that", "one ought to recognise that", "attention should be drawn to the fact that"],
  "plays a crucial role": ["has been instrumental", "serves a vital function", "is a central factor", "remains essential"],
  "plays an important role": ["holds significant value", "serves as a key component", "remains a significant factor"],
  "has played a crucial role": ["has been very instrumental", "has served a vital function", "has occupied a central place"],
  "played a crucial role": ["proved to be a central element"],
  "played a critical and transformative role": ["was decisive and radical", "proved both critical and transformative", "had a profound and far-reaching impact"],
  "played a significant and ongoing role": ["have been very influential and consistent", "remained a persistent and significant force"],
  "played a major role": ["significantly contributed", "proved to be a key factor"],
  "has been another major factor": ["has also been a key driver", "is another critical element", "represents yet another important contributor"],
  "have significantly contributed": ["have played a major role", "have been instrumental", "have had a substantial impact on"],
  "significantly contributed": ["had a substantial impact on"],
  "significantly increased": ["substantially raised", "boosted considerably", "markedly improved", "increased by a great deal"],
  "significantly reduced": ["substantially lowered", "cut considerably", "brought down markedly"],
  "significant transformation": ["tremendous change", "marked transformation", "substantial shift", "sweeping transformation"],
  "significant impact": ["profound effect", "substantial influence", "considerable impact", "far-reaching impact"],
  "significant increase": ["substantial rise", "marked increase", "considerable growth", "sharp upturn"],
  "a direct and profound impact": ["a powerful and immediate effect", "a direct and far-reaching influence"],
  "has greatly improved": ["has markedly enhanced", "has substantially bettered", "has seen a major improvement in"],
  "greatly improved": ["markedly enhanced", "substantially bettered", "notably advanced"],
  "in response,": ["To address this,", "In reaction to this,", "The response was that", "This prompted a situation where"],
  "in response to this demand": ["to satisfy this demand", "to meet the rising demand", "in order to address this growing need"],
  "over time,": ["With time,", "As years went by,", "In the long run,", "Gradually,"],
  "over time": ["with time", "as years went by", "gradually", "in the course of time"],
  "this paper discusses": ["the paper explains", "this paper examines", "this paper explores the role of"],
  "the major factors": ["the key drivers", "the primary forces", "the main contributing elements"],
  "highly restricted": ["placed a high limit on", "severely limited", "tightly controlled"],
  "primarily designed to serve": ["mostly meant to serve", "largely intended to benefit", "chiefly aimed at serving"],
  "leaving the majority of": ["and left majority of", "which resulted in most of", "thus excluding most"],
  "limited opportunities": ["few opportunities", "scarce prospects", "restricted access to opportunity"],
  "faced a shortage of": ["was short of", "experienced a deficit in", "lacked sufficient"],
  "making secondary education inaccessible": ["and as such, secondary education was not affordable", "which meant secondary education remained out of reach"],
  "powerful tool for promoting": ["potent instrument of fostering", "strong vehicle for advancing", "effective means of promoting"],
  "deliberate government policies": ["planned government action", "intentional government strategies", "targeted policy interventions"],
  "community initiatives": ["local programs", "grassroots efforts", "community-driven interventions"],
  "international support": ["international assistance", "donor support", "aid from the global community"],
  "contributed to a steady and rapid expansion": ["led to a consistent and accelerated growth", "fuelled continuous and swift growth", "been instrumental in steady and accelerated expansion"],
  "enrolment rates increased significantly": ["the enrolment rates rose tremendously", "enrolment figures grew substantially", "student registration increased sharply"],
  "more schools were established across the country": ["the number of schools built across the country increased", "additional schools were set up throughout the nation"],
  "one of the most influential factors": ["one of the most significant influences", "among the most powerful drivers"],
  "successive governments have prioritized": ["various governments have given much emphasis to", "one administration after another has placed priority on"],
  "key component of national development strategies": ["pillar of their national development plans", "cornerstone of the national development agenda"],
  "this commitment is reflected in": ["this promise is enshrined in", "this dedication is evident in", "the commitment manifests through"],
  "policy frameworks aimed at improving": ["policy frameworks designed to enhance", "regulatory measures intended to improve"],
  "one major initiative was": ["among these significant programs was", "a landmark step was"],
  "reduced the cost burden on parents": ["brought the cost burden on parents to a much lower level", "eased the financial load on parents considerably"],
  "enabled students from low-income families": ["gave students with low-income families an opportunity", "allowed learners from disadvantaged backgrounds"],
  "increasing transition rates from primary school": ["which boosted transition rates out of primary school", "thereby improving the flow from primary into secondary education"],
  "consistently invested in infrastructure development": ["been investing in the development of infrastructures", "sustained investment in building educational facilities"],
  "construction of classrooms, laboratories": ["building of classrooms, laboratories", "establishment of classrooms, science labs"],
  "teacher recruitment and training": ["recruiting and training of teachers", "hiring and professional development of educators"],
  "adequate teaching personnel": ["sufficient number of teaching staff", "the required level of qualified educators"],
  "provision of textbooks and learning materials": ["delivery of textbooks and learning materials", "supply of books and instructional resources"],
  "consistent efforts demonstrate": ["successive moves prove", "these sustained measures illustrate"],
  "central role of government commitment": ["focal place of government dedication", "pivotal position of government involvement"],
  "driving educational expansion": ["in the educational growth", "advancing educational development"],
  "had a direct and profound impact": ["directly and significantly influenced", "had an immediate and far-reaching effect on"],
  "by removing school fees": ["it eliminated school fees and", "through the abolition of school fees"],
  "the government significantly increased enrolment": ["the government enrolled many students", "there was a sharp rise in student enrolment"],
  "leading to a sharp rise": ["and consequently the number", "resulting in a dramatic surge"],
  "created considerable pressure": ["posed some serious strain", "exerted intense pressure", "placed significant demands"],
  "the government and other stakeholders were compelled": ["this forced the government and other stakeholders", "the government alongside other actors had no choice but"],
  "expand existing secondary schools and establish new ones": ["extend the current secondary schools and create new ones", "enlarge existing facilities and open new institutions"],
  "to accommodate the growing demand": ["to satisfy the demand", "to meet the increasing need"],
  "increased dramatically": ["shot up by a great margin", "surged rapidly", "rose very sharply"],
  "intensifying the need for": ["which further added pressure on", "amplifying the demand for"],
  "multiplier effect": ["multiplier effect", "cascading impact"],
  "education planners had to adjust policies": ["education planners were forced in turn to revise policies", "those responsible for planning had to adapt their strategies"],
  "allocate more resources": ["make more investment", "direct additional funding", "channel more resources"],
  "communities and private investors also stepped in": ["the communities and individual investors intervened", "local groups and private investors also contributed"],
  "support the expansion process": ["promote the process of growth", "facilitate further expansion"],
  "particularly in rural and underserved areas": ["especially in the rural and underprivileged regions", "particularly in remote and disadvantaged communities"],
  "reflects a strong tradition of": ["is one of the strong traditions of", "embodies a deep-rooted practice of"],
  "community participation and collective responsibility": ["community involvement and shared responsibility", "civic engagement and mutual accountability"],
  "local communities took the initiative": ["it became the initiative of the local people", "communities at the grassroot level took it upon themselves"],
  "where government support was either limited or unavailable": ["where the government was either very scarce or nonexistent", "in areas where state support was minimal or absent"],
  "contributed land, labor, building materials, and financial resources": ["donated land, labor, building materials, and finances", "pooled together land, manpower, construction materials, and funding"],
  "ensured that children had access to education": ["so that children were guaranteed access to education", "to make certain that children could attend school"],
  "initially operated as harambee schools": ["started as Harambee schools", "began as community-founded Harambee schools"],
  "before later being integrated into": ["and were then included in", "before eventually joining"],
  "this grassroots approach significantly increased": ["this decentralized strategy drastically expanded", "this bottom-up approach substantially raised"],
  "the number of secondary schools across the country": ["the secondary schools nationwide", "the total count of secondary schools across the nation"],
  "especially in remote areas": ["and more so in the rural regions", "particularly in far-flung communities"],
  "fostered a strong sense of ownership": ["created a feeling of ownership", "cultivated a deep sense of belonging"],
  "encouraged accountability and sustainability": ["promoted accountability and sustainability", "strengthened both accountability and long-term viability"],
  "most unique and impactful drivers": ["most distinctive and effective factors", "most remarkable and meaningful contributors"],
  "increasingly valued in kenyan society": ["there has been increased appreciation of education in the Kenyan society", "has gained growing recognition within Kenyan society"],
  "key pathway to economic success and social mobility": ["important avenue to economic prosperity and social elevation", "vital route to financial stability and upward mobility"],
  "essential qualifications required for employment": ["necessary qualifications that are needed in employment", "the credentials essential for entering the job market"],
  "further academic advancement": ["subsequent academic growth", "continued educational progression"],
  "growing awareness has led to": ["increased awareness is the fact that", "heightened consciousness has resulted in"],
  "a significant increase in demand": ["a substantial rise in demand", "a marked growth in demand"],
  "rise steadily": ["been increasing steadily", "showing consistent growth"],
  "rise significantly": ["grew substantially", "increased markedly"],
  "a tool for improving living standards": ["a means of enhancing the standards of living", "a pathway to better quality of life"],
  "basic necessity rather than a privilege": ["a need and not a luxury", "an essential requirement rather than a luxury"],
  "shift in mindset has played a major role": ["change of attitude has significantly contributed", "transformation in outlook has been a driving force"],
  "a powerful force behind": ["a formidable force in", "a strong driving factor behind"],
  "rapid population growth": ["rapid growth in population", "fast-growing population"],
  "the population continues to increase": ["the population is ever-growing", "population figures keep climbing"],
  "the number of school-age children also rises significantly": ["the number of children of school-age is also increasing considerably", "school-going age children are also increasing in number"],
  "created sustained pressure": ["put a long term strain", "exerted persistent pressure"],
  "provide adequate learning opportunities": ["offer sufficient learning opportunities", "ensure enough educational places are available"],
  "forced to expand educational infrastructure": ["had to increase educational infrastructure", "been compelled to grow the educational infrastructure"],
  "constructing new schools and enlarging existing ones": ["building new schools and increasing the size of existing ones", "erecting new institutions while expanding those already in place"],
  "high population density areas": ["high population density areas", "densely populated zones"],
  "urban and peri-urban regions": ["urban and peri-urban areas", "metropolitan and surrounding areas"],
  "influenced policy decisions": ["affected the policy makers", "shaped government priorities"],
  "increased budget allocation for education": ["allocation of more budget towards education", "a bigger share of the national budget going to education"],
  "demographic changes have played": ["demographic changes have been very influential and consistent in", "shifts in population dynamics have been pivotal in"],
  "economic growth and industrialization": ["economic growth and industrialization", "the expansion of the economy and industrial development"],
  "there is an increasing demand for": ["the need to hire", "there is growing demand for"],
  "a skilled and educated workforce": ["a skilled and educated workforce", "well-trained human capital"],
  "capable of supporting various sectors": ["which is able to serve many sectors of the economy", "equipped to contribute to different economic sectors"],
  "such as industry, commerce, and public service": ["such as industry, commerce, and public service", "including manufacturing, trade, and government service"],
  "foundational knowledge and skills": ["essential knowledge and skills", "the basic competencies"],
  "more students are motivated to enroll": ["the number of students joining secondary schools increases", "a greater number of students are encouraged to register"],
  "in order to improve their chances": ["with an aim of increasing their likelihood", "so as to enhance their prospects"],
  "securing stable and well-paying jobs": ["getting stable and well paying employment", "landing dependable and well-remunerated positions"],
  "raised their minimum qualification requirements": ["increased the qualification requirements", "set higher minimum educational standards"],
  "making secondary education a basic necessity": ["where secondary education has become a simple requirement", "so that secondary education is now considered a baseline need"],
  "aligned education policies with economic goals": ["aligned the education policies with the economic interests", "linked educational planning to economic priorities"],
  "emphasizing the importance of human capital development": ["whereby the focus on human capital development is emphasised", "placing emphasis on developing the workforce"],
  "encouraged further investment": ["has been matched with more investments", "has spurred additional investment"],
  "curriculum improvements and infrastructure development": ["improvement of the curriculum and development of infrastructures", "curriculum updates alongside facility construction"],
  "widely recognized by policymakers and stakeholders": ["well identified by the policymakers and the stakeholders", "broadly acknowledged across policy and stakeholder circles"],
  "unlike boarding schools": ["the day schools are cheaper than the boarding schools since", "compared to boarding schools,"],
  "more affordable because they eliminate": ["cost less as they remove", "cheaper since they do away with"],
  "accommodation and feeding costs": ["the costs of accommodation and feeding", "boarding and meal expenses"],
  "accessible to a larger segment of the population": ["accessible to more people in the population", "available to a wider cross-section of society"],
  "reducing the distance students must travel": ["minimising the amount of distance which children have to cover", "shortening the travel distance for learners"],
  "reduced dropout rates and increased enrolment": ["low rates of dropouts and higher enrolment", "fewer students quitting and greater student uptake"],
  "actively promoted the development of": ["been in vigorous encouragement of the creation of", "taken active steps to foster the establishment of"],
  "a cost-effective strategy for expanding access": ["a cost-efficient approach to increase accessibility", "an affordable means of broadening access"],
  "international organizations and development partners": ["the international organizations and development partners", "global agencies and development collaborators"],
  "financial and technical assistance": ["financial and technical support", "both monetary and technical resources"],
  "improving access and quality of education": ["enhancing the access and quality of education", "strengthening both reach and quality in education"],
  "construct schools, train teachers, and provide learning materials": ["build schools, educate teachers and make available learning resources", "establish schools, develop teachers professionally, and supply materials"],
  "facilitated policy reforms and capacity building": ["also spurred reforms in policies and capacity building", "supported both policy change and institutional strengthening"],
  "complemented government efforts": ["supplemented government efforts", "reinforced state initiatives"],
  "especially in underserved areas": ["particularly in the underserved regions", "above all in marginalised communities"],
  "introduced best practices and innovations": ["brought the best practices and innovations", "contributed new methodologies and creative approaches"],
  "efforts to promote gender equality": ["gender equality initiatives", "the push for gender parity"],
  "cultural practices and socio-economic factors": ["cultural reasons as well as social-economic influence", "both cultural norms and socio-economic constraints"],
  "limited girls' access to education": ["girls were not allowed to access education", "restricted educational opportunities for girls"],
  "government policies and advocacy programs": ["government policies and advocacy programs", "policy measures and public awareness campaigns"],
  "addressed these challenges by promoting equal access": ["have focused on enhancing equal access", "have tackled these barriers by championing equitable access"],
  "reduced dropout rates among girls": ["minimised the dropout rates in girls", "lowered the rate at which girls leave school"],
  "more girls are now able to enroll in and complete": ["there are increased girls who can attend and graduate", "a greater number of girls can now access and finish"],
  "improved overall participation rates": ["enhanced the general rates of participation", "boosted participation across the board"],
  "a combination of interrelated factors": ["a combination of interrelated factors", "multiple interconnected forces"],
  "have significantly increased access to education": ["there is access to education that has been enhanced greatly", "have considerably widened access to schooling"],
  "complemented government efforts by establishing schools at the grassroots level": ["been used to supplement the government program by creating schools at grassroots level", "reinforced government programs by setting up schools at the community level"],
  "have also played a vital role": ["have also been of crucial support and contribution", "have likewise made meaningful contributions"],
  "challenges such as overcrowding, limited resources, and teacher shortages persist": ["problems like overcrowding, shortage of resources and shortage of teachers are still in existence", "issues including overcrowded classrooms, scarce resources, and inadequate staffing remain"],
  "continued investment and effective policy implementation are therefore necessary": ["more investment and proper policy implementation is thus required", "sustained funding and well-executed policies remain essential"],
  "sustain progress and improve the quality": ["continue with the gains and enhance the quality", "maintain the momentum and raise the standard"],
  "this situation is often described as": ["this has been termed as", "what is commonly referred to as"],
  "where expansion at one level of education leads to growth at the next level": ["whereby a growth at a certain level of education results in growth at a higher level of education", "in which expansion at one educational tier drives growth at the subsequent tier"],
  "has undergone": ["has experienced", "has gone through", "has seen"],
  "recognized education as": ["saw the value of education as", "identified education as"],
  "have contributed to": ["have fuelled", "have facilitated", "have been responsible for"],
  "various policy frameworks": ["a number of policy frameworks", "several regulatory instruments"],
  "it is worth noting that": ["one should observe that", "a key point is that", "notably,"],
  "it is evident that": ["clearly,", "it appears that", "one can observe that"],
  "this highlights the importance of": ["this underlines the value of", "this draws attention to the significance of"],
  "this underscores the need for": ["this makes clear the necessity of", "this points to the requirement for"],
  "it can be argued that": ["one might contend that", "a reasonable case exists that", "there is ground to suggest that"],
  "it is widely recognized that": ["most observers agree that", "there is broad consensus that"],
  "in order to": ["so as to", "with the aim of", "to"],
  "due to the fact that": ["because", "since", "given that", "as"],
  "a wide range of": ["numerous", "many different", "a broad array of"],
  "a significant number of": ["many", "a considerable number of", "numerous"],
  "on the other hand": ["conversely", "by contrast", "from another perspective"],
  "in the context of": ["within the scope of", "regarding", "with respect to"],
  "with regard to": ["concerning", "in relation to", "as for"],
  "in terms of": ["regarding", "concerning", "with respect to", "as regards"],
  "has the potential to": ["could", "may well", "is capable of"],
  "there is a growing need for": ["there is increasing demand for", "the need for ... is rising"],
  "this suggests that": ["this indicates that", "this implies that", "this points to the likelihood that"],
  "serves as a": ["functions as a", "acts as a", "operates as a"],
  "in light of": ["given", "considering", "in view of"],
  "take into account": ["consider", "bear in mind", "factor in"],
  "give rise to": ["produce", "bring about", "generate"],
  "a key factor": ["a central element", "a vital component", "a leading driver"],
  "the extent to which": ["how far", "the degree to which", "how much"],
  "it is essential to": ["it remains vital to", "it is necessary to", "one must"],
  "on a global scale": ["worldwide", "across the globe", "internationally"],
  "in recent years": ["over recent years", "in the past several years", "of late"],
  "the fact that": ["the reality that", "the circumstance that"],
  "have the ability to": ["can", "are able to", "possess the capacity to"],
  "at the same time": ["simultaneously", "concurrently", "in parallel"],
  "contribute to the": ["feed into the", "support the", "add to the"],
  "are often": ["tend to be", "are frequently", "are commonly"],
  "is often": ["tends to be", "is frequently", "is commonly"],
  "play a vital role in": ["are central to", "remain essential to", "are indispensable to"],
  "has become increasingly": ["has grown ever more", "is now more ... than before"],
  "cannot be overstated": ["is hard to exaggerate", "is immense", "deserves strong emphasis"],
  "a comprehensive approach": ["a thorough strategy", "a wide-ranging method", "an all-encompassing plan"],
  "the importance of": ["the value of", "the significance of", "the weight of"],
  "there is a need to": ["it is necessary to", "one must", "steps are required to"],
  "is characterized by": ["features", "is marked by", "is defined by"],
  "is influenced by": ["is shaped by", "is affected by", "is moulded by"],
  "poses a significant challenge": ["presents a serious difficulty", "constitutes a major hurdle", "represents a formidable obstacle"],
  "a deeper understanding of": ["greater insight into", "a more thorough grasp of", "a richer appreciation of"],
  "have been widely studied": ["have attracted extensive scholarly attention", "have been the subject of considerable research"],
  "to a large extent": ["in great measure", "largely", "to a considerable degree"],
  "from various perspectives": ["from multiple angles", "through different lenses", "from a range of viewpoints"],
  "sheds light on": ["illuminates", "clarifies", "brings into focus"],
  "paves the way for": ["opens the door to", "lays the groundwork for", "creates the conditions for"],
  "remains a subject of debate": ["continues to be contested", "is still disputed", "remains contentious"],
  "raises important questions about": ["prompts serious enquiry into", "invites scrutiny of", "poses pressing questions regarding"],
};

// Pre-sorted by phrase length (longest first) for matching
export const SORTED_PHRASE_KEYS: string[] = Object.keys(PHRASE_SUBSTITUTIONS)
  .sort((a, b) => b.length - a.length);

export const SYNONYM_BANK: Record<string, string[]> = {
  "significant": ["substantial", "considerable", "notable", "major", "marked"],
  "important": ["essential", "vital", "critical", "key", "crucial"],
  "crucial": ["essential", "vital", "pivotal", "critical"],
  "major": ["substantial", "considerable", "key", "primary"],
  "rapid": ["swift", "accelerated", "fast", "brisk"],
  "considerable": ["substantial", "significant", "notable"],
  "limited": ["restricted", "scarce", "insufficient"],
  "inadequate": ["insufficient", "deficient", "lacking"],
  "effective": ["efficient", "productive", "successful"],
  "powerful": ["potent", "strong", "formidable"],
  "growing": ["expanding", "rising", "mounting"],
  "increasing": ["rising", "expanding", "mounting", "escalating"],
  "steady": ["consistent", "gradual", "sustained"],
  "sharp": ["dramatic", "abrupt", "sudden"],
  "direct": ["immediate", "clear", "straightforward"],
  "profound": ["deep", "far-reaching", "sweeping"],
  "unique": ["distinctive", "unparalleled", "remarkable"],
  "various": ["multiple", "numerous", "several", "diverse"],
  "particular": ["specific", "distinct", "special"],
  "relevant": ["pertinent", "applicable", "appropriate"],
  "widespread": ["extensive", "broad", "pervasive"],
  "sufficient": ["adequate", "enough", "ample"],
  "excessive": ["disproportionate", "undue", "extreme"],
  "evident": ["apparent", "clear", "observable"],
  "primary": ["principal", "main", "chief", "foremost"],
  "subsequent": ["following", "later", "ensuing"],
  "modern": ["contemporary", "present-day", "current"],
  "traditional": ["conventional", "established", "long-standing"],
  "comprehensive": ["thorough", "extensive", "wide-ranging"],
  "fundamental": ["basic", "core", "central", "foundational"],
  "complex": ["intricate", "multifaceted", "layered"],
  "diverse": ["varied", "mixed", "heterogeneous"],
  "robust": ["strong", "sturdy", "resilient"],
  "emerging": ["developing", "rising", "budding"],
  "ongoing": ["continuing", "sustained", "unfolding"],
  "overall": ["general", "broad", "aggregate"],
  "notable": ["remarkable", "noteworthy", "striking"],
  "essential": ["indispensable", "necessary", "core"],
  "critical": ["vital", "decisive", "central"],
  "positive": ["beneficial", "favourable", "constructive", "advantageous"],
  "negative": ["adverse", "detrimental", "unfavourable", "harmful"],
  "large": ["sizeable", "substantial", "extensive"],
  "small": ["modest", "minor", "limited"],
  "new": ["novel", "fresh", "emerging"],
  "key": ["central", "vital", "core", "principal"],
  "global": ["worldwide", "international"],
  "local": ["domestic", "regional", "community-level"],
  "economic": ["financial", "fiscal", "monetary"],
  "social": ["societal", "communal", "public"],
  "political": ["governmental", "civic", "state-level"],
  "environmental": ["ecological", "nature-related"],
  "cultural": ["sociocultural", "civilisational", "social", "communal"],
  "natural": ["organic", "inherent", "innate"],
  "specific": ["particular", "precise", "definite"],
  "general": ["broad", "overall", "wide-ranging"],
  "common": ["prevalent", "widespread", "frequent"],
  "recent": ["latest", "new", "fresh"],
  "potential": ["possible", "prospective", "likely"],
  "severe": ["serious", "grave", "acute"],
  "weak": ["fragile", "feeble", "inadequate"],
  "harmful": ["damaging", "detrimental", "injurious"],
  "beneficial": ["advantageous", "helpful", "favorable"],
  "sustainable": ["enduring", "lasting", "long-term"],
  "stable": ["steady", "consistent", "secure"],
  "vulnerable": ["susceptible", "exposed", "at risk"],
  "dominant": ["prevailing", "leading", "principal"],
  "productive": ["efficient", "fruitful", "constructive"],
  "competitive": ["rivalrous", "aggressive", "market-driven"],
  "favorable": ["advantageous", "beneficial", "supportive"],
  "unfavorable": ["adverse", "disadvantageous", "detrimental"],
  "basic": ["fundamental", "elementary", "foundational"],
  "substantial": ["considerable", "meaningful", "sizable"],
  "transformation": ["change", "shift", "transition", "overhaul"],
  "expansion": ["growth", "development", "extension", "widening"],
  "shortage": ["deficit", "shortfall", "scarcity", "lack"],
  "opportunity": ["prospect", "chance", "opening"],
  "opportunities": ["prospects", "openings", "avenues"],
  "initiative": ["effort", "program", "undertaking"],
  "framework": ["structure", "model", "system"],
  "mechanism": ["process", "system", "method"],
  "strategy": ["plan", "approach", "tactic"],
  "impact": ["effect", "influence", "consequence"],
  "factor": ["element", "variable", "determinant"],
  "factors": ["elements", "contributors", "drivers", "aspects"],
  "challenge": ["difficulty", "hurdle", "obstacle"],
  "challenges": ["difficulties", "obstacles", "hurdles", "barriers"],
  "sector": ["field", "area", "domain"],
  "sectors": ["areas", "domains", "fields", "segments"],
  "development": ["advancement", "evolution"],
  "perception": ["view", "impression", "understanding"],
  "awareness": ["consciousness", "recognition", "understanding"],
  "implication": ["consequence", "ramification", "bearing"],
  "implications": ["consequences", "ramifications", "repercussions"],
  "transition": ["shift", "move", "changeover"],
  "majority": ["bulk", "greater part", "most"],
  "barrier": ["obstacle", "hurdle", "impediment"],
  "barriers": ["obstacles", "impediments", "hindrances"],
  "contribution": ["part", "addition", "role"],
  "countries": ["nations", "states", "economies"],
  "country": ["nation", "state", "economy"],
  "goods": ["products", "commodities", "merchandise"],
  "services": ["programs", "offerings"],
  "decades": ["years", "recent decades"],
  "economies": ["economic systems", "markets", "financial systems"],
  "growth": ["expansion", "increase", "rise"],
  "trade": ["commerce", "exchange", "commercial activity"],
  "investment": ["capital inflow", "funding", "financial commitment"],
  "technology": ["technological innovation", "technical advancement"],
  "exchange": ["interaction", "interchange", "transfer"],
  "system": ["network", "model"],
  "markets": ["commercial arenas", "trading systems", "marketplaces"],
  "production": ["output", "manufacturing", "yield"],
  "income": ["revenue", "earnings", "proceeds"],
  "industries": ["sectors", "branches", "fields"],
  "structures": ["frameworks", "systems", "arrangements"],
  "corporations": ["companies", "firms", "enterprises"],
  "companies": ["firms", "enterprises", "corporations"],
  "workers": ["employees", "labourers", "the workforce"],
  "regions": ["areas", "zones", "territories"],
  "communities": ["populations", "groups", "localities"],
  "consumers": ["buyers", "customers", "purchasers"],
  "resources": ["assets", "means", "capital"],
  "policies": ["measures", "regulations", "directives"],
  "standards": ["benchmarks", "criteria", "norms"],
  "conditions": ["circumstances", "situations", "environments"],
  "practices": ["methods", "approaches", "procedures"],
  "concern": ["worry", "anxiety", "fear"],
  "concerns": ["issues", "worries", "matters of concern"],
  "benefits": ["advantages", "gains", "merits"],
  "advantages": ["benefits", "merits", "strengths"],
  "drawbacks": ["disadvantages", "shortcomings", "limitations"],
  "disadvantages": ["drawbacks", "shortcomings", "weaknesses"],
  "effects": ["outcomes", "consequences", "results"],
  "issues": ["problems", "matters", "topics"],
  "problems": ["issues", "difficulties", "complications"],
  "solutions": ["remedies", "answers", "responses"],
  "trends": ["patterns", "tendencies", "shifts"],
  "gap": ["divide", "disparity", "discrepancy"],
  "role": ["part"],
  "extent": ["degree", "scope", "range"],
  "aspect": ["dimension", "facet", "element"],
  "aspects": ["dimensions", "facets", "elements"],
  "approach": ["method", "strategy", "technique"],
  "result": ["outcome", "consequence", "effect"],
  "measure": ["step", "action", "initiative"],
  "activity": ["operation", "undertaking", "pursuit"],
  "activities": ["operations", "undertakings", "pursuits"],
  "level": ["level"],
  "rates": ["levels", "figures", "proportions"],
  "demand": ["need"],
  "quality": ["standard", "calibre", "grade"],
  "wealth": ["prosperity", "affluence", "riches"],
  "inequality": ["disparity", "imbalance", "unevenness"],
  "instability": ["volatility", "turbulence", "unpredictability"],
  "demonstrates": ["shows", "illustrates", "reveals", "exhibits"],
  "indicates": ["suggests", "points to", "signals", "implies"],
  "contributes": ["adds", "lends", "assists", "aids"],
  "facilitate": ["enable", "support", "assist"],
  "enhance": ["improve", "strengthen", "boost"],
  "address": ["tackle", "handle", "deal with"],
  "establish": ["set up", "build", "create"],
  "implement": ["execute", "carry out", "enact"],
  "promote": ["encourage", "advance", "foster"],
  "ensure": ["guarantee", "secure", "confirm"],
  "reflect": ["mirror", "show", "indicate"],
  "compel": ["force", "oblige", "require", "drive"],
  "accommodate": ["cater for", "house", "hold", "support"],
  "utilize": ["use", "employ", "harness"],
  "prioritize": ["emphasize", "focus on", "rank"],
  "recognize": ["acknowledge", "identify", "appreciate"],
  "persist": ["continue", "endure", "remain"],
  "sustain": ["maintain", "preserve", "uphold"],
  "motivate": ["encourage", "inspire", "drive", "spur"],
  "provides": ["offers", "delivers", "supplies"],
  "requires": ["demands", "necessitates", "calls for"],
  "examines": ["investigates", "analyses", "explores"],
  "suggests": ["implies", "proposes", "recommends"],
  "reveals": ["uncovers", "discloses", "highlights"],
  "remain": ["continue", "endure", "stay"],
  "achieved": ["attained", "accomplished", "reached"],
  "supported": ["reinforced", "backed", "bolstered"],
  "refers": ["relates", "pertains", "alludes"],
  "involves": ["entails", "encompasses", "includes"],
  "includes": ["encompasses", "comprises", "incorporates"],
  "created": ["established", "generated", "produced"],
  "introduced": ["brought in", "initiated", "established"],
  "produced": ["generated", "yielded", "brought about"],
  "transformed": ["reshaped", "altered", "changed", "restructured"],
  "improved": ["enhanced", "strengthened", "upgraded", "bettered"],
  "reduced": ["lowered", "diminished", "decreased", "cut"],
  "attracted": ["drawn", "lured", "brought in"],
  "experienced": ["seasoned", "skilled", "veteran"],
  "participated": ["taken part", "engaged", "been involved"],
  "affected": ["influenced", "impacted", "shaped"],
  "dominated": ["controlled", "prevailed over", "overshadowed"],
  "raised": ["elevated", "lifted", "heightened"],
  "considered": ["regarded", "viewed", "deemed"],
  "caused": ["triggered", "prompted", "brought about"],
  "contributed": ["added", "helped lead"],
  "influenced": ["shaped", "affected", "swayed"],
  "generated": ["produced", "created", "yielded"],
  "resulted": ["culminated"],
  "allowed": ["enabled", "permitted", "granted"],
  "enabled": ["allowed", "empowered", "facilitated"],
  "maintained": ["preserved", "sustained", "upheld"],
  "obtained": ["acquired", "secured", "gained"],
  "expanded": ["broadened", "widened", "extended"],
  "highlighted": ["underscored", "emphasised", "drawn attention to"],
  "emphasized": ["stressed", "underlined", "underscored"],
  "questioned": ["challenged", "contested", "scrutinised"],
  "adopted": ["embraced", "taken up", "implemented"],
  "noted": ["observed", "remarked", "pointed out"],
  "argued": ["contended", "asserted", "maintained"],
  "claimed": ["asserted", "maintained", "stated"],
  "showed": ["demonstrated", "revealed", "illustrated"],
  "led": ["led"],
  "faced": ["encountered", "confronted", "dealt with"],
  "depends": ["hinges", "rests", "relies"],
  "strengthened": ["reinforced", "bolstered", "fortified"],
  "weakened": ["undermined", "eroded", "diminished"],
  "emerged": ["arose", "surfaced", "appeared"],
  "significantly": ["substantially", "considerably", "markedly", "greatly"],
  "particularly": ["especially", "specifically", "notably"],
  "primarily": ["mainly", "chiefly", "largely", "predominantly"],
  "consequently": ["therefore", "as a result", "hence"],
  "subsequently": ["later", "afterwards", "thereafter"],
  "dramatically": ["sharply", "steeply", "enormously", "vastly"],
  "consistently": ["steadily", "regularly", "continually"],
  "increasingly": ["progressively", "ever more", "to a growing extent"],
  "effectively": ["efficiently", "successfully", "competently"],
  "highly": ["extremely", "very", "exceedingly", "immensely"],
  "often": ["frequently", "commonly", "regularly"],
  "typically": ["usually", "generally", "commonly"],
  "generally": ["broadly", "typically", "on the whole"],
  "largely": ["mostly", "primarily", "to a great extent"],
  "mainly": ["principally", "chiefly", "predominantly"],
  "rapidly": ["swiftly", "quickly", "at a fast pace"],
  "heavily": ["substantially", "considerably", "to a great degree"],
  "merely": ["simply", "only", "just"],
  "strongly": ["firmly", "powerfully", "forcefully"],
  "directly": ["immediately", "straightforwardly", "in a direct manner"],
  "widely": ["broadly", "extensively", "commonly"],
  "clearly": ["evidently", "plainly", "unmistakably"],
  "especially": ["particularly", "notably", "above all"],
  "greatly": ["considerably", "immensely", "tremendously"],
  "severely": ["acutely", "seriously", "gravely"],
  "deeply": ["profoundly", "intensely", "thoroughly"],
  "eventually": ["ultimately", "in time", "in the end"],
  "successfully": ["effectively", "competently", "with success"],
  "actively": ["energetically", "vigorously", "dynamically"],
  "specifically": ["precisely", "in particular", "explicitly"],
  "alarming": ["troubling", "disturbing", "worrying", "concerning"],
  "appropriate": ["suitable", "fitting", "proper"],
  "accurate": ["precise", "exact", "correct"],
  "broad": ["wide", "expansive", "far-reaching"],
  "enormous": ["vast", "immense", "massive"],
  "extreme": ["severe", "intense", "drastic"],
  "frequent": ["common", "regular", "repeated"],
  "obvious": ["clear", "apparent", "self-evident"],
  "persistent": ["enduring", "lasting", "chronic"],
  "promising": ["encouraging", "hopeful", "favorable"],
  "strict": ["rigorous", "stringent", "tight"],
  "urgent": ["pressing", "immediate", "critical"],
  "viable": ["feasible", "practical", "workable"],
  "visible": ["noticeable", "observable", "evident"],
  "ambitious": ["bold", "aspiring", "far-reaching"],
  "controversial": ["contentious", "debated", "disputed"],
  "convincing": ["compelling", "persuasive", "forceful"],
  "costly": ["expensive", "high-priced", "burdensome"],
  "dangerous": ["hazardous", "risky", "perilous"],
  "dependent": ["reliant", "conditional", "contingent"],
  "drastic": ["severe", "extreme", "radical"],
  "entire": ["whole", "complete", "full"],
  "gradual": ["incremental", "progressive", "step-by-step"],
  "inevitable": ["unavoidable", "inescapable", "certain"],
  "intense": ["strong", "fierce", "vigorous"],
  "massive": ["enormous", "huge", "vast"],
  "respective": ["individual", "own", "separate"],
  "simultaneous": ["concurrent", "parallel"],
  "strategic": ["calculated", "planned", "tactical"],
  "troubling": ["concerning", "worrying", "unsettling"],
  "uncertain": ["unclear", "ambiguous", "doubtful"],
  "underlying": ["fundamental", "root", "core"],
  "unprecedented": ["unmatched", "novel", "historic"],
  "basis": ["foundation", "ground", "premise"],
  "capacity": ["ability", "capability", "potential"],
  "circumstance": ["situation", "condition", "context"],
  "component": ["element", "part", "constituent"],
  "concept": ["idea", "notion", "principle"],
  "consequence": ["outcome", "result", "effect"],
  "debate": ["discussion", "discourse", "argument"],
  "decline": ["drop", "reduction", "decrease"],
  "dimension": ["aspect", "facet", "scope"],
  "emphasis": ["focus", "stress", "weight"],
  "environment": ["setting", "surroundings", "context"],
  "era": ["period", "epoch", "age"],
  "estimate": ["assessment", "projection", "calculation"],
  "evidence": ["proof", "indication", "data"],
  "example": ["instance", "illustration", "case"],
  "feature": ["characteristic", "attribute", "quality"],
  "incentive": ["motivation", "stimulus", "driver"],
  "indicator": ["marker", "signal", "measure"],
  "insight": ["understanding", "perception", "awareness"],
  "instance": ["example", "case", "occurrence"],
  "institution": ["organization", "body", "establishment"],
  "interaction": ["exchange", "engagement", "interplay"],
  "intervention": ["action", "measure", "step"],
  "investigation": ["study", "inquiry", "examination"],
  "link": ["connection", "tie", "association"],
  "method": ["technique", "approach", "procedure"],
  "notion": ["idea", "concept", "belief"],
  "objective": ["goal", "aim", "target"],
  "obstacle": ["barrier", "hurdle", "impediment"],
  "outcome": ["result", "consequence", "finding"],
  "pattern": ["trend", "tendency", "regularity"],
  "period": ["phase", "stage", "span"],
  "perspective": ["viewpoint", "standpoint", "angle"],
  "phenomenon": ["occurrence", "event", "trend"],
  "policy": ["regulation", "guideline", "directive"],
  "portion": ["share", "fraction", "segment"],
  "priority": ["focus", "concern", "emphasis"],
  "progress": ["advancement", "headway", "improvement"],
  "proportion": ["share", "ratio", "fraction"],
  "rationale": ["reasoning", "logic", "justification"],
  "region": ["area", "territory", "zone"],
  "resource": ["asset", "supply", "source"],
  "response": ["reaction", "answer"],
  "scope": ["range", "extent", "breadth"],
  "shift": ["change", "move"],
  "source": ["origin", "root", "cause"],
  "structure": ["framework", "system", "arrangement"],
  "tendency": ["trend", "inclination", "pattern"],
  "tension": ["friction", "strain", "conflict"],
  "theme": ["topic", "subject", "motif"],
  "threat": ["danger", "risk", "hazard"],
  "trend": ["pattern", "shift", "movement"],
  "variation": ["difference", "divergence", "fluctuation"],
  "volume": ["amount", "quantity", "level"],
  "achieve": ["attain", "accomplish", "reach"],
  "acknowledge": ["recognize", "admit", "accept"],
  "adapt": ["adjust", "modify", "tailor"],
  "advocate": ["promote", "champion", "support"],
  "analyze": ["examine", "assess", "evaluate"],
  "apply": ["employ", "utilize", "implement"],
  "assess": ["evaluate", "gauge", "appraise"],
  "assume": ["presume", "suppose", "expect"],
  "attempt": ["try", "endeavor", "seek"],
  "attribute": ["ascribe", "assign", "credit"],
  "cite": ["reference", "mention", "quote"],
  "compare": ["contrast", "juxtapose", "parallel"],
  "comprise": ["include", "consist of", "encompass"],
  "conduct": ["carry out", "perform", "execute"],
  "confirm": ["verify", "validate", "corroborate"],
  "connect": ["link", "relate", "associate"],
  "consider": ["examine", "reflect on", "weigh"],
  "constitute": ["form", "make up", "represent"],
  "construct": ["build", "develop", "create"],
  "consume": ["use", "utilize", "deplete"],
  "contribute": ["add", "contribute"],
  "demonstrate": ["show", "illustrate", "prove"],
  "derive": ["obtain", "draw", "extract"],
  "describe": ["depict", "outline", "characterize"],
  "detect": ["identify", "spot", "uncover"],
  "determine": ["decide", "shape", "define"],
  "diminish": ["reduce", "lessen", "weaken"],
  "display": ["exhibit", "show", "present"],
  "document": ["record", "chronicle", "log"],
  "eliminate": ["remove", "eradicate", "abolish"],
  "emerge": ["appear", "surface", "arise"],
  "employ": ["use", "utilize", "apply"],
  "encounter": ["face", "meet", "come across"],
  "evaluate": ["assess", "appraise", "judge"],
  "examine": ["investigate", "analyze", "study"],
  "exhibit": ["display", "show", "manifest"],
  "foster": ["encourage", "promote", "nurture"],
  "function": ["operate", "work", "serve"],
  "hamper": ["hinder", "obstruct", "impede"],
  "identify": ["recognize", "pinpoint", "detect"],
  "illustrate": ["demonstrate", "show", "highlight"],
  "imply": ["suggest", "indicate", "infer"],
  "improve": ["enhance", "upgrade", "strengthen"],
  "incorporate": ["include", "embed", "integrate"],
  "indicate": ["suggest", "signal", "point to"],
  "initiate": ["begin", "launch", "start"],
  "investigate": ["explore", "probe", "examine"],
  "involve": ["include", "entail", "require"],
  "justify": ["validate", "defend", "support"],
  "limit": ["restrict", "constrain", "curb"],
  "minimize": ["reduce", "lessen", "diminish"],
  "mitigate": ["lessen", "alleviate", "reduce"],
  "modify": ["alter", "adjust", "change"],
  "monitor": ["track", "observe", "oversee"],
  "neglect": ["overlook", "ignore", "disregard"],
  "observe": ["notice", "see", "witness"],
  "operate": ["function", "run", "work"],
  "perceive": ["view", "regard", "see"],
  "produce": ["generate", "create", "yield"],
  "propose": ["suggest", "recommend", "put forward"],
  "pursue": ["follow", "seek", "strive for"],
  "recommend": ["suggest", "advise", "advocate"],
  "reduce": ["decrease", "lower", "cut"],
  "regulate": ["control", "govern", "manage"],
  "reinforce": ["strengthen", "bolster", "support"],
  "reject": ["dismiss", "refuse", "decline"],
  "relate": ["connect", "link", "pertain"],
  "rely": ["depend", "count on", "lean on"],
  "replace": ["substitute", "swap", "exchange"],
  "represent": ["reflect", "signify", "illustrate"],
  "require": ["demand", "call for"],
  "resolve": ["settle", "address", "fix"],
  "restrict": ["limit", "constrain", "confine"],
  "retain": ["keep", "maintain", "preserve"],
  "reveal": ["disclose", "uncover", "expose"],
  "select": ["choose", "pick", "opt for"],
  "stimulate": ["encourage", "promote", "spur"],
  "suggest": ["propose", "recommend", "indicate"],
  "support": ["backing", "aid"],
  "transform": ["reshape", "alter", "overhaul"],
  "validate": ["confirm", "verify", "substantiate"],
  "yield": ["produce", "generate", "deliver"],
  "accordingly": ["therefore", "thus", "hence"],
  "briefly": ["concisely", "in short", "succinctly"],
  "constantly": ["continually", "perpetually", "always"],
  "currently": ["presently", "at present", "now"],
  "entirely": ["completely", "wholly", "fully"],
  "essentially": ["fundamentally", "basically", "at its core"],
  "extremely": ["highly", "immensely", "remarkably"],
  "formally": ["officially", "properly", "systematically"],
  "immediately": ["promptly", "at once", "right away"],
  "inevitably": ["unavoidably", "naturally", "certainly"],
  "initially": ["at first", "originally", "to begin with"],
  "notably": ["remarkably", "especially", "in particular"],
  "potentially": ["possibly", "conceivably", "perhaps"],
  "precisely": ["exactly", "accurately", "specifically"],
  "predominantly": ["mainly", "largely", "primarily"],
  "previously": ["earlier", "before", "formerly"],
  "properly": ["correctly", "adequately", "suitably"],
  "rarely": ["seldom", "infrequently", "hardly ever"],
  "relatively": ["comparatively", "somewhat", "fairly"],
  "roughly": ["approximately", "about", "around"],
  "solely": ["exclusively", "only", "purely"],
  "ultimately": ["finally", "in the end", "eventually"],
  "virtually": ["nearly", "almost", "practically"],
};

export const PROTECTED_WORDS: ReadonlySet<string> = new Set(["a", "about", "above", "accordingly", "additionally", "after", "all", "also", "alternatively", "although", "am", "among", "an", "and", "are", "as", "at", "be", "been", "before", "being", "below", "between", "both", "but", "by", "can", "concurrently", "consequently", "could", "course", "despite", "did", "do", "does", "during", "each", "fair", "for", "from", "furthermore", "granted", "had", "has", "have", "having", "he", "helps", "her", "hers", "herself", "him", "himself", "his", "how", "however", "i", "if", "importantly", "in", "interestingly", "into", "is", "issue", "it", "its", "itself", "least", "less", "matters", "may", "me", "meanwhile", "might", "mine", "more", "moreover", "most", "must", "my", "myself", "nevertheless", "no", "nonetheless", "nor", "not", "oddly", "of", "on", "only", "or", "other", "our", "ours", "ourselves", "own", "plus", "practice", "related", "remember", "same", "shall", "she", "should", "simply", "simultaneously", "since", "so", "still", "subsequently", "such", "surprisingly", "than", "that", "the", "their", "theirs", "them", "themselves", "then", "therefore", "these", "they", "this", "those", "though", "through", "to", "too", "under", "unless", "unnoticed", "upon", "us", "very", "was", "we", "were", "what", "when", "where", "whereas", "whether", "which", "while", "who", "whom", "whose", "why", "will", "with", "within", "without", "would", "yes", "yet", "you", "your", "yours", "yourself"]);

export const PROTECTED_PATTERNS: RegExp[] = [
  new RegExp("\\([A-Z][a-z]+.*?,\\s*\\d{4}\\)"),
  new RegExp("\\b\\d{4}\\b"),
  new RegExp("\\b[A-Z]{2,}\\b"),
  new RegExp("https?://\\S+"),
  new RegExp("\\b[A-Z][a-z]+\\s(?:&\\s)?[A-Z][a-z]+"),
];