import type { Rule } from '../baseRule';
import type { Sentence, Issue } from '../../core/types';

/**
 * Extended common misspellings beyond confusionSets.
 * Catches 100+ common typos and spelling errors.
 */

const MISSPELLINGS: Record<string, string> = {
  // Common typos
  'becuase': 'because', 'becasue': 'because', 'becouse': 'because',
  'wich': 'which', 'whch': 'which', 'wich': 'which',
  'comming': 'coming', 'comeing': 'coming',
  'happend': 'happened', 'happended': 'happened',
  'diffrent': 'different', 'diffferent': 'different', 'diferent': 'different',
  'importent': 'important', 'importnat': 'important',
  'knowlege': 'knowledge', 'knowlegde': 'knowledge',
  'managment': 'management', 'managament': 'management',
  'explaination': 'explanation',
  'experiance': 'experience', 'expirience': 'experience',
  'profesional': 'professional', 'proffesional': 'professional',
  'posible': 'possible', 'possable': 'possible',
  'probaly': 'probably', 'propably': 'probably', 'probablly': 'probably',
  'realy': 'really', 'reallly': 'really',
  'responsable': 'responsible',
  'strenght': 'strength', 'strenghth': 'strength',
  'sucess': 'success', 'succes': 'success',
  'surprize': 'surprise',
  'togehter': 'together', 'togather': 'together',
  'truely': 'truly',
  'unfortunatly': 'unfortunately', 'unfortuantly': 'unfortunately',
  'usefull': 'useful', 'usful': 'useful',
  'ussually': 'usually', 'usally': 'usually',
  'wether': 'whether',
  'wich': 'which',
  'writen': 'written', 'writting': 'writing',
  'noticable': 'noticeable', 'noticable': 'noticeable',
  'occassion': 'occasion', 'occaison': 'occasion',
  'persue': 'pursue',
  'prefered': 'preferred', 'prefering': 'preferring',
  'refered': 'referred', 'refering': 'referring',
  'rythm': 'rhythm', 'rythym': 'rhythm',
  'sentance': 'sentence',
  'similiar': 'similar', 'similer': 'similar',
  'speach': 'speech',
  'suprise': 'surprise', 'surprize': 'surprise',
  'temperture': 'temperature', 'temprature': 'temperature',
  'therefor': 'therefore',
  'thru': 'through',
  'transfered': 'transferred',
  'vaccum': 'vacuum', 'vaccuum': 'vacuum',
  'wensday': 'wednesday',
  'abscence': 'absence',
  'accross': 'across',
  'agressive': 'aggressive', 'aggresive': 'aggressive',
  'apparantly': 'apparently', 'apparentely': 'apparently',
  'athelete': 'athlete',
  'basicly': 'basically', 'basicaly': 'basically',
  'buisness': 'business', 'bussiness': 'business',
  'calender': 'calendar', 'calander': 'calendar',
  'catagory': 'category', 'categorie': 'category',
  'charactor': 'character',
  'collegue': 'colleague', 'collaegue': 'colleague',
  'commitee': 'committee', 'comittee': 'committee',
  'completly': 'completely', 'completeley': 'completely',
  'concieve': 'conceive',
  'consciense': 'conscience',
  'consistant': 'consistent',
  'critisism': 'criticism', 'critisism': 'criticism',
  'defintion': 'definition', 'defination': 'definition',
  'develope': 'develop',
  'dissapear': 'disappear', 'dissappear': 'disappear',
  'dissapoint': 'disappoint', 'dissappoint': 'disappoint',
  'embarass': 'embarrass', 'embarras': 'embarrass',
  'excercise': 'exercise', 'exersize': 'exercise',
  'existance': 'existence',
  'familar': 'familiar', 'familliar': 'familiar',
  'finaly': 'finally', 'fianally': 'finally',
  'foriegn': 'foreign', 'forein': 'foreign',
  'fourty': 'forty',
  'freind': 'friend', 'frend': 'friend',
  'fulfil': 'fulfill',
  'gaurd': 'guard',
  'grammer': 'grammar',
  'harrass': 'harass', 'harrass': 'harass',
  'hieght': 'height', 'heigth': 'height',
  'humourous': 'humorous',
  'hygeine': 'hygiene',
  'immediatly': 'immediately', 'immediatley': 'immediately',
  'incidently': 'incidentally',
  'independance': 'independence',
  'innoculate': 'inoculate',
  'inteligent': 'intelligent', 'inteligence': 'intelligence',
  'intresting': 'interesting', 'intresting': 'interesting',
  'iresistible': 'irresistible',
  'jellous': 'jealous',
  'judgement': 'judgment',
  'langauge': 'language', 'lanugage': 'language',
  'lenght': 'length',
  'liason': 'liaison',
  'libary': 'library', 'libray': 'library',
  'liscense': 'license', 'lisence': 'license',
  'maintainance': 'maintenance', 'maintenace': 'maintenance',
  'millenium': 'millennium', 'milennium': 'millennium',
  'mischevious': 'mischievous',
  'misspel': 'misspell',
  'naturaly': 'naturally',
  'neccessity': 'necessity',
  'negligable': 'negligible',
  'nieghbor': 'neighbor', 'neighbour': 'neighbor',
  'occurrance': 'occurrence',
  'paralel': 'parallel', 'parrallel': 'parallel',
  'parliment': 'parliament',
  'particulary': 'particularly',
  'percieve': 'perceive',
  'permissable': 'permissible',
  'persistant': 'persistent',
  'personaly': 'personally',
  'pharoah': 'pharaoh',
  'playright': 'playwright',
  'posession': 'possession', 'posesion': 'possession',
  'potatos': 'potatoes',
  'preceed': 'precede',
  'privelege': 'privilege',
  'pronounciation': 'pronunciation',
  'publically': 'publicly',
  'recomend': 'recommend', 'reccommend': 'recommend',
  'relevent': 'relevant', 'relavent': 'relevant',
  'religous': 'religious',
  'remeber': 'remember', 'rember': 'remember',
  'repitition': 'repetition',
  'resistence': 'resistance',
  'restarant': 'restaurant', 'restaraunt': 'restaurant',
  'scisor': 'scissors',
  'seize': 'seize',
  'sincerly': 'sincerely',
  'speek': 'speak',
  'stomache': 'stomach',
  'succede': 'succeed',
  'supercede': 'supersede',
  'tatoo': 'tattoo',
  'technicaly': 'technically',
  'tendancy': 'tendency',
  'tomatos': 'tomatoes',
  'tounge': 'tongue',
  'tyrany': 'tyranny',
  'underate': 'underrate',
  'uneccessary': 'unnecessary', 'unnecesary': 'unnecessary',
  'vegetable': 'vegetable',
  'visious': 'vicious',
  'wieght': 'weight', 'wiegh': 'weigh',
  'wellfare': 'welfare',
  'whereever': 'wherever',
  'wich': 'which',
};

export const extendedSpellingRule: Rule = {
  id: 'extended_spelling',
  description: 'Catches 100+ common misspellings and typos',

  apply(sentence: Sentence): Issue[] {
    const issues: Issue[] = [];

    for (const token of sentence.tokens) {
      if (token.kind !== 'word') continue;
      const fix = MISSPELLINGS[token.norm];
      if (!fix) continue;
      // Preserve original case pattern
      const replacement = token.text[0] === token.text[0].toUpperCase()
        ? fix[0].toUpperCase() + fix.slice(1)
        : fix;
      issues.push({
        ruleId: 'spelling_common',
        message: `Misspelling: "${token.text}" → "${replacement}"`,
        severity: 'error',
        start: token.start,
        end: token.end,
        replacements: [replacement],
        confidence: 0.96,
        category: 'Spelling',
        sentenceIndex: 0,
      });
    }

    return issues;
  },
};
