/**
 * V2 Enhancement Data — Merged from Humara v2 backup
 * Populates the 6 stub constants in engine.js with real data.
 */

// ═══════════════════════════════════════════════════════════════════
// PHRASE_COMPRESS — 421 phrase-level compressions (wordy → concise)
// Format: { "verbose phrase": ["alt1", "alt2", ...] }
// ═══════════════════════════════════════════════════════════════════

export const PHRASE_COMPRESS = {
  'plays a significant role in':['serves an important function in','is instrumental in','has a major influence on','matters greatly in','contributes meaningfully to'],
  'plays a crucial role in':['is vital to','holds a central place in','is essential to the functioning of','remains critical to'],
  'plays a vital role in':['proves essential to','is integral to','has deep significance in','stands at the heart of'],
  'plays an important role in':['holds significance in','has a meaningful impact on','contributes to','adds value to'],
  'plays a key role in':['is central to','serves as a cornerstone of','is a major factor in','figures prominently in'],
  'it is important to note that':['one should recognize that','a key point here is that','notably','worth mentioning is that'],
  'it is worth noting that':['notably','one observation worth highlighting is that','a point of interest here is that','it bears mention that'],
  'it should be noted that':['one should keep in mind that','a relevant point is that','what stands out is that','notably'],
  'it is essential to':['one must','it remains necessary to','there is a clear need to','the priority should be to'],
  'it is crucial to':['one must','it remains vital to','the focus should be on','the emphasis needs to be on'],
  'it is imperative to':['one must urgently','the pressing need is to','the situation demands that','a high priority is to'],
  'in today\'s world':['in the current landscape','in modern times','across contemporary society','in the present day'],
  'in today\'s society':['in the modern era','in contemporary culture','across present-day communities','within modern civilization'],
  'in today\'s fast-paced world':['given how rapidly things move today','in an era defined by constant change','as the pace of life continues to quicken'],
  'in today\'s digital age':['in an era shaped by digital tools','within the modern digital landscape','as digital technology matures'],
  'in order to':['to','so as to','with the aim of','for the purpose of'],
  'due to the fact that':['because','since','given that','as a result of the fact that','owing to'],
  'owing to the fact that':['because','since','as','given that'],
  'a wide range of':['many different','numerous','a broad variety of','a diverse set of','an assortment of'],
  'a large number of':['many','numerous','a considerable quantity of','quite a few'],
  'a significant number of':['many','a sizable portion of','quite a substantial group of','no small number of'],
  'a growing number of':['more and more','an increasing share of','a rising count of','a steadily expanding group of'],
  'a substantial amount of':['a great deal of','considerable','extensive quantities of','a heavy portion of'],
  'has the potential to':['can','may well','holds the capacity to','is positioned to'],
  'have the potential to':['can','may well','hold the capacity to','are positioned to'],
  'has the ability to':['can','is able to','possesses the means to','is equipped to'],
  'on the other hand':['conversely','by contrast','then again','alternatively','at the same time'],
  'in addition to':['besides','along with','beyond','on top of','coupled with'],
  'in addition to this':['furthermore','what adds to this','building on this point','beyond this'],
  'as a result':['consequently','therefore','because of this','this led to','thus'],
  'as a result of':['because of','owing to','stemming from','on account of','arising from'],
  'as a consequence':['because of this','following from this','in response','accordingly'],
  'it is evident that':['clearly','the evidence shows that','it becomes apparent that','what the data reveals is that'],
  'it is clear that':['clearly','the evidence confirms that','what emerges is that','there is little doubt that'],
  'it is apparent that':['one can see that','it becomes obvious that','the conclusion is that','discernibly'],
  'it is widely recognized that':['scholars generally agree that','the consensus is that','there is broad agreement that','many accept that'],
  'it is generally accepted that':['most experts agree that','the prevailing view is that','common understanding holds that'],
  'for example':['for instance','as an example','to illustrate','consider the case of'],
  'for instance':['as an example','to illustrate','one such case is','take the example of'],
  'in the context of':['regarding','when considering','with respect to','within the framework of'],
  'in the realm of':['within','across the field of','throughout','in the domain of'],
  'in terms of':['regarding','with respect to','when it comes to','concerning'],
  'with regard to':['concerning','relating to','about','regarding','as for'],
  'with respect to':['concerning','regarding','in relation to','about'],
  'in light of':['given','considering','based on','taking into account'],
  'in light of the above':['given the foregoing','based on what has been discussed','with all of this in mind'],
  'in light of these findings':['based on these results','considering what the data shows','building on these observations'],
  'on the basis of':['based on','drawing from','relying on','grounded in'],
  'from the perspective of':['according to','as seen by','through the lens of','in the view of'],
  'it can be argued that':['one argument is that','a reasonable case exists for','the position can be taken that','there is reason to believe that'],
  'it could be argued that':['some might contend that','a case can be made that','one might reason that'],
  'it can be concluded that':['the conclusion here is that','what follows is that','the logical outcome is that'],
  'it is necessary to':['one must','the situation requires','there is a need to','the task calls for'],
  'it has been shown that':['research confirms that','studies indicate that','evidence supports the claim that','findings demonstrate that'],
  'it has been demonstrated that':['research has confirmed that','studies have established that','the evidence makes clear that'],
  'it has been observed that':['observations indicate that','what has been noticed is that','data shows that'],
  'a key factor in':['a major element of','something that strongly influences','a primary driver of','an essential ingredient in'],
  'the primary objective of':['the main goal of','the central aim of','what is chiefly sought through','the first priority of'],
  'the main purpose of':['the chief aim of','the core intention behind','what this seeks to accomplish is','the basic goal of'],
  'the purpose of this study':['this study aims to','what the research sets out to do','the goal of this investigation'],
  'the aim of this paper':['this paper sets out to','what this paper intends to explore','the focus of this paper'],
  'the findings suggest that':['the results show that','what was found reveals that','the evidence indicates that'],
  'the results indicate that':['the data suggests that','what the results reveal is that','the outcome points to the conclusion that'],
  'the data shows that':['the numbers confirm that','what the data reveals is that','the evidence from the data is that'],
  'the literature suggests that':['prior studies indicate that','the existing body of work points to','published research has found that'],
  'the evidence suggests that':['the available evidence points to','what the evidence shows is that','a reading of the evidence indicates that'],
  'according to recent studies':['recent research has found that','studies carried out recently indicate','the latest investigations reveal'],
  'according to the findings':['based on what was found','the results reveal that','the data shows that'],
  'this paper examines':['this paper looks into','the focus here is on','the present work investigates'],
  'this paper explores':['this paper investigates','the present work looks at','the focus of this paper is on'],
  'this study aims to':['the goal of this study is to','this research sets out to','what the study tries to do is'],
  'this study investigates':['the present research looks into','this work examines','the investigation here focuses on'],
  'this essay argues that':['the argument put forward here is that','what this essay contends is that','the position taken in this essay is that'],
  'in conclusion':['to sum up','ultimately','all things considered','bringing everything together'],
  'to conclude':['in summary','to bring this to a close','looking at the full picture'],
  'in summary':['to wrap up','altogether','taken as a whole','bringing the main points together'],
  'to summarize':['bringing the key points together','looking at the full picture','putting it all together'],
  'taking everything into account':['weighing all the factors','when all aspects are considered','looking at the complete picture'],
  'it is widely acknowledged that':['most people agree that','there is general consensus that','scholars broadly accept that'],
  'it has become increasingly clear that':['it is becoming more and more obvious that','there is growing recognition that','the trend is pointing toward the conclusion that'],
  'it is often argued that':['a common argument is that','many contend that','a frequently heard claim is that'],
  'moreover':['furthermore','beyond that','what is more','adding to this','on top of that'],
  'furthermore':['in addition','moreover','beyond this','adding to the above'],
  'nevertheless':['even so','still','regardless','in spite of this','all the same'],
  'nonetheless':['even so','despite that','regardless','still'],
  'however':['that said','yet','still','but','even so'],
  'consequently':['as a result','therefore','because of this','it follows that'],
  'subsequently':['after that','following this','later','next'],
  'therefore':['for this reason','hence','as a result','accordingly','thus'],
  'thus':['as a result','in this way','so','accordingly'],
  'hence':['for that reason','as such','consequently','this is why'],
  'additionally':['also','besides this','on top of that','in addition'],
  'similarly':['in a similar fashion','along the same lines','likewise','in much the same way'],
  'likewise':['in a similar way','along the same lines','similarly','by the same token'],
  'specifically':['more precisely','in particular','to be exact','to narrow it down'],
  'significantly':['considerably','substantially','meaningfully','to a notable degree'],
  'undoubtedly':['without question','certainly','there is no doubt that','clearly'],
  'ultimately':['in the end','at the end of the day','when all is said and done','finally'],
  'essentially':['at its core','fundamentally','in basic terms','in essence'],
  'fundamentally':['at its foundation','at the most basic level','in essence','at the root'],
  'increasingly':['more and more','to a growing extent','with growing frequency','at an accelerating pace'],
  'particularly':['especially','above all','most notably','in particular'],
  'notably':['in particular','worth highlighting','especially','most strikingly'],
  'interestingly':['what stands out','a curious point is that','a noteworthy observation is that','of note'],
  'critically':['at the most important level','what matters most here','at the core of the issue','centrally'],
  'arguably':['one could say','it might be fair to say','a strong case can be made that','by some measures'],
  'evidently':['as the evidence shows','it appears that','based on what can be observed','from the evidence'],
  'typically':['in most cases','as a general rule','ordinarily','under normal circumstances'],
  'generally':['in most cases','as a rule','broadly speaking','for the most part'],
  'primarily':['chiefly','mainly','above all','first and foremost'],
  'predominantly':['mostly','largely','for the greater part','in the main'],
  'effectively':['in practice','for all practical purposes','in a meaningful way'],
  'accordingly':['as such','in response to this','in keeping with this','along these lines'],
  'conversely':['on the flip side','by contrast','in the opposite case','looking at it from the other direction'],
  'simultaneously':['at the same time','in parallel','concurrently','side by side'],
  'comprehensive':['thorough','extensive','in-depth','complete'],
  'facilitate':['make easier','support','help bring about','enable','assist in'],
  'facilitates':['makes easier','supports','helps bring about','enables'],
  'utilize':['use','make use of','employ','draw on'],
  'utilizes':['uses','makes use of','employs','draws on'],
  'utilizing':['using','making use of','employing','drawing on'],
  'implement':['put into practice','carry out','apply','execute'],
  'implements':['puts into practice','carries out','applies','executes'],
  'implementing':['putting into practice','carrying out','applying','rolling out'],
  'implementation':['execution','rollout','application in practice','deployment'],
  'demonstrate':['show','illustrate','make clear','bring to light'],
  'demonstrates':['shows','illustrates','makes clear','brings to light'],
  'enhancing':['improving','boosting','raising the quality of','strengthening'],
  'enhance':['improve','boost','raise the quality of','strengthen'],
  'enhances':['improves','boosts','raises the quality of','strengthens'],
  'encompasses':['includes','covers','spans','stretches across'],
  'encompass':['include','cover','span','take in'],
  'encompassing':['including','covering','taking in'],
  'delve into':['look closely at','examine in detail','dig into','get into the details of'],
  'delves into':['looks closely at','examines in detail','digs into','gets into the details of'],
  'navigate':['work through','find a way through','deal with','manage'],
  'navigating':['working through','finding a way through','dealing with','managing'],
  'navigates':['works through','finds a way through','deals with','manages'],
  'landscape':['environment','scene','field','setting'],
  'paradigm':['model','framework','approach','way of thinking'],
  'paradigm shift':['fundamental change','major change in approach','rethinking of the model','shift in thinking'],
  'multifaceted':['complex','many-sided','varied','diverse'],
  'nuanced':['subtle','layered','detailed','complex in nature'],
  'overarching':['broad','central','overall','spanning'],
  'pivotal':['critical','central','key','decisive'],
  'paramount':['critical','essential','vital','foremost'],
  'robust':['strong','solid','well-built','resilient'],
  'pertinent':['relevant','applicable','to the point','fitting'],
  'intricate':['complex','elaborate','detailed','involved'],
  'meticulous':['careful','thorough','precise','painstaking'],
  'profound':['deep','far-reaching','significant','serious'],
  'profoundly':['deeply','in a far-reaching way','in a significant manner','seriously'],
  'unprecedented':['extraordinary','remarkable','exceptional','unparalleled'],
  'aligns with':['matches','is consistent with','fits with','goes hand in hand with'],
  'is aligned with':['matches','is consistent with','corresponds to','goes along with'],
  'coupled with':['together with','alongside','combined with'],
  'in conjunction with':['together with','alongside','in combination with','working with'],
  'in tandem with':['alongside','together with','working in step with'],
  'in the wake of':['following','after','in the aftermath of','coming after'],
  'in the face of':['when confronted with','despite','up against','in response to'],
  'in the midst of':['during','while in the middle of','amid','surrounded by'],
  'at the forefront of':['leading the way in','at the front of','pioneering','driving progress in'],
  'at the heart of':['central to','at the core of','right at the center of','the essence of'],
  'at the expense of':['to the detriment of','while sacrificing','at the cost of'],
  'by virtue of':['because of','thanks to','owing to','through'],
  'serve as':['function as','act as','work as','operate as'],
  'serves as':['functions as','acts as','works as','operates as'],
  'shed light on':['clarify','help explain','bring greater understanding to','illuminate'],
  'sheds light on':['clarifies','helps explain','brings greater understanding to','offers insight into'],
  'give rise to':['lead to','result in','bring about','produce'],
  'gives rise to':['leads to','results in','brings about','produces'],
  'take into account':['consider','keep in mind','factor in','allow for'],
  'takes into account':['considers','factors in','keeps in mind','allows for'],
  'taking into account':['considering','factoring in','keeping in mind','allowing for'],
  'bring about':['cause','lead to','produce','set in motion'],
  'brings about':['causes','leads to','produces','sets in motion'],
  'lends itself to':['is well suited for','works well with','is fitting for'],
  'paves the way for':['creates the conditions for','opens the door to','sets the stage for','makes possible'],
  'is characterized by':['is defined by','is marked by','features','is known for'],
  'is indicative of':['points to','signals','suggests','is a sign of'],
  'is reflective of':['mirrors','reflects','shows','is a reflection of'],
  'is synonymous with':['is closely linked to','is often equated with','stands for'],
  'is contingent upon':['depends on','hinges on','is conditional on','relies on'],
  'is predicated on':['is based on','rests on','relies on','is grounded in'],
  'is attributed to':['is credited to','is linked to','is thought to come from','is believed to result from'],
  'is conducive to':['supports','favors','promotes','helps create conditions for'],
  'is tantamount to':['amounts to','is equivalent to','is practically the same as'],
  'is akin to':['resembles','is similar to','has parallels with'],
  'is inherent in':['is built into','comes naturally with','is a natural part of','exists within'],
  'with that being said':['that said','even so','given that','bearing that in mind'],
  'having said that':['that said','even so','still','despite that observation'],
  'first and foremost':['above all','most importantly','at the outset','before anything else'],
  'last but not least':['finally','and just as important','to close with','one more point worth raising'],
  'by and large':['on the whole','generally speaking','for the most part','overall'],
  'all in all':['on the whole','taking everything together','overall','when considered together'],
  'as a whole':['overall','in its entirety','altogether','taken as one'],
  'as such':['for that reason','therefore','because of this','given this'],
  'to that end':['with that goal in mind','toward that objective','in pursuit of that aim'],
  'to this end':['with this goal in mind','for this purpose','toward this aim'],
  'for the purpose of':['in order to','so as to','with the goal of','aimed at'],
  'with the aim of':['intending to','hoping to','setting out to','with the goal of'],
  'with a view to':['intending to','with the purpose of','aiming to','looking to'],
  'as opposed to':['rather than','instead of','in contrast to','unlike'],
  'as compared to':['relative to','in comparison with','next to','measured against'],
  'in comparison to':['relative to','when measured against','compared with','next to'],
  'prior to':['before','ahead of','preceding','in advance of'],
  'subsequent to':['after','following','once','later than'],
  'in the absence of':['without','lacking','when there is no','if missing'],
  'in the presence of':['when faced with','given the existence of','where there is','with the involvement of'],
  'a plethora of':['many','a wide range of','a wealth of','an abundance of'],
  'a myriad of':['many','countless','a large variety of','a wide assortment of'],
  'a multitude of':['many','a great number of','a broad range of','an extensive set of'],
  'the vast majority of':['most','nearly all','the bulk of','the greater part of'],
  'an integral part of':['a key piece of','a necessary component of','central to','built into'],
  'a cornerstone of':['a foundation of','a pillar of','a key element of','something central to'],
  'a driving force behind':['a major factor in','a key contributor to','one of the main reasons for'],
  'the extent to which':['how much','the degree to which','how far','the measure of'],
  'the degree to which':['how much','the extent that','the level at which'],
  'the manner in which':['the way','how','the method by which'],
  'the notion that':['the idea that','the belief that','the concept that'],
  'the concept of':['the idea of','the principle of','the theory behind'],
  'the phenomenon of':['the occurrence of','the pattern of','the event of'],
  'the implications of':['what follows from','the consequences of','the effects of','what this means for'],
  'despite the fact that':['even though','although','while it is true that','notwithstanding the fact that'],
  'regardless of the fact that':['even though','no matter that','irrespective of the fact that'],
  'including but not limited to':['such as','among them','including for example','examples include'],
  'needless to say':['of course','as expected','clearly','naturally'],
  'it goes without saying that':['naturally','of course','as one would expect'],
  'there is no denying that':['without question','it is hard to dispute that','no one can question that'],
  'there is a growing consensus that':['more and more experts agree that','the view is increasingly shared that','opinion is moving toward the idea that'],
  'to a certain extent':['in part','to some degree','partially','up to a point'],
  'to a large extent':['largely','to a great degree','for the most part','substantially'],
  'to a significant extent':['considerably','to a meaningful degree','noticeably','substantially'],
  'in this regard':['on this point','in this respect','regarding this','here'],
  'in this context':['here','in this particular case','under these conditions','against this backdrop'],
  'in this manner':['in this way','through this approach','by doing so'],
  'along these lines':['in a similar vein','following the same logic','with that in mind'],
  'within the scope of':['within the bounds of','limited to','falling under','within the range of'],
  'a wide array of':['many different','a varied collection of','a broad set of'],
  'a diverse range of':['many types of','a varied set of','several forms of'],
  'is of particular importance':['is especially important','matters a great deal','stands out as significant','holds special relevance'],
  'is of utmost importance':['is absolutely critical','ranks as the highest priority','matters above all else'],
  'mitigate the effects of':['reduce the impact of','lessen the consequences of','ease the effects of'],
  'mitigate':['reduce','limit','ease','lessen'],
  'exacerbate':['worsen','intensify','make worse','aggravate'],
  'exacerbates':['worsens','intensifies','makes worse','aggravates'],
  'perpetuate':['continue','keep alive','maintain','sustain over time'],
  'perpetuates':['continues','keeps alive','maintains','sustains over time'],
  'underscore':['highlight','emphasize','stress','draw attention to'],
  'underscores':['highlights','emphasizes','stresses','draws attention to'],
  'elucidate':['clarify','explain','make clear','shed light on'],
  'elucidates':['clarifies','explains','makes clear','sheds light on'],
  'necessitate':['require','call for','make necessary','demand'],
  'necessitates':['requires','calls for','makes necessary','demands'],
  'juxtapose':['place side by side','compare directly','set against each other'],
  'transcend':['go beyond','rise above','move past','exceed'],
  'transcends':['goes beyond','rises above','moves past','exceeds'],
  'embody':['represent','stand for','reflect','capture'],
  'embodies':['represents','stands for','reflects','captures'],
  'endeavor':['effort','attempt','undertaking','pursuit'],
  'endeavors':['efforts','attempts','undertakings','pursuits'],
  'proliferation':['spread','rapid growth','expansion','rise'],
  'ramification':['consequence','outcome','effect','result'],
  'ramifications':['consequences','outcomes','effects','results'],
  'discourse':['discussion','debate','conversation','dialogue'],
  'dichotomy':['divide','split','contrast','division'],
  'a holistic approach':['a complete approach','a full-picture approach','a well-rounded method'],
  'holistic':['complete','all-around','comprehensive','well-rounded'],
  'synergy':['combined effect','cooperation','collaborative benefit','shared advantage'],
  'catalyze':['trigger','spark','accelerate','set off'],
  'catalyzes':['triggers','sparks','accelerates','sets off'],
  'streamline':['simplify','make more efficient','slim down','optimize'],
  'streamlines':['simplifies','makes more efficient','slims down','optimizes'],
  'bolster':['strengthen','support','reinforce','shore up'],
  'bolsters':['strengthens','supports','reinforces','shores up'],
  'stakeholder':['interested party','participant','contributor','those involved'],
  'stakeholders':['interested parties','participants','contributors','involved parties'],
  'leverage':['use','draw on','employ','harness'],
  'leverages':['uses','draws on','employs','harnesses'],
  'leveraging':['using','drawing on','employing','harnessing'],
  'optimize':['improve','refine','fine-tune','make the most of'],
  'optimizes':['improves','refines','fine-tunes','makes the most of'],
  'methodology':['method','approach','system','process'],
  'framework':['structure','system','approach','model'],
  'infrastructure':['underlying systems','foundation','supporting structures','base systems'],
  'trajectory':['path','direction','course','trend'],
  'trajectory of':['path of','direction of','course of','trend in'],
  'the trajectory of':['the path of','the direction of','the course of'],
  'ecosystem':['network','environment','system','community'],
  'a wide spectrum of':['a broad range of','many kinds of','an extensive set of'],
  'spectrum':['range','variety','span'],
  'disparity':['gap','difference','imbalance','inequality'],
  'disparities':['gaps','differences','imbalances','inequalities'],
  'the disparity between':['the gap between','the difference between','the imbalance between'],
  'the interplay between':['the interaction between','the relationship between','how these factors work together'],
  'the intersection of':['the overlap between','the convergence of','the junction of'],
  'a pivotal moment in':['a turning point in','a key juncture in','a decisive stage in'],
  'on a global scale':['worldwide','across the globe','at the international level'],
  'at the global level':['internationally','across the world','on a worldwide basis'],
  'across various sectors':['in many fields','throughout different industries','in a range of areas'],
  'across multiple dimensions':['along several axes','in more than one way','from multiple angles'],
  'within the broader context of':['set against the wider background of','in the larger picture of','as part of the wider story of'],
  'poses a significant challenge':['presents a major difficulty','creates a serious obstacle','stands as a considerable hurdle'],
  'poses significant challenges':['presents major difficulties','creates serious obstacles','leads to considerable hurdles'],
  'presents a unique opportunity':['opens up a rare chance','offers a distinctive opening','brings a special occasion to'],
  'it remains to be seen whether':['the outcome is still uncertain regarding whether','the question remains whether','only time will tell if'],
  'in the long run':['over time','in the long term','when looking further ahead','down the line'],
  'in the short term':['immediately','over the near future','in the coming period'],
  'is a testament to':['shows','proves','stands as proof of','is evidence of'],
  'bears testament to':['speaks to','reflects','serves as proof of'],
  'are inextricably linked':['are closely connected','are tightly joined','cannot be separated'],
  'inextricably linked to':['closely tied to','tightly connected to','bound up with'],
  'shape the future of':['influence the direction of','determine what lies ahead for','steer the course of'],
  'remains a contentious issue':['continues to generate debate','remains widely disputed','is still hotly debated'],
  'the crux of the matter':['the central issue','the core problem','the heart of the question'],
  'the bottom line is':['what it comes down to is','the key takeaway is','in plain terms'],
  'it is incumbent upon':['the responsibility falls to','it is the duty of','it is up to'],
  'yield significant results':['produce meaningful outcomes','deliver strong results','generate notable gains'],
  'yields':['produces','generates','delivers','results in'],
  'empirical evidence suggests':['data from studies indicates','observable evidence points to the conclusion','measurements and observations suggest'],
  'empirical evidence':['data from observation','factual evidence','evidence based on measurements'],
  'empirical':['observation-based','data-driven','based on direct evidence'],
  'theoretical framework':['underlying theory','conceptual basis','foundational model'],
  'socioeconomic':['social and economic','economic and social'],
  'socioeconomic factors':['social and economic factors','economic and social conditions'],
  'interdisciplinary':['cross-field','spanning multiple disciplines','drawing from different fields'],
  'multidisciplinary':['involving several fields','cross-disciplinary','drawing on many areas'],
  'sustainable development':['development that lasts','long-term and responsible growth','growth that preserves future resources'],
  'renewable energy':['clean energy','energy from renewable sources','green power'],
  'cognitive development':['mental growth','intellectual development','growth of thinking skills'],
  'evidence-based':['backed by research','supported by data','grounded in evidence'],
  'evidence-based practice':['practice grounded in research','data-supported methods','research-backed practice'],
  'peer-reviewed':['evaluated by experts','reviewed by other researchers','expert-assessed'],
  'digital transformation':['shift toward digital systems','adoption of digital tools','move toward technology-driven processes'],
  'monetary policy':['central bank policy','interest rate and money supply decisions','financial policy set by the central bank'],
  'fiscal policy':['government spending and tax policy','budgetary policy','public finance decisions'],
  'economic growth':['economic expansion','financial growth','economic development'],
  'gross domestic product':['total national output','the economy\'s total production','national economic output'],
  'risk management':['managing exposure to risk','risk mitigation planning','strategies for handling risk'],
  'return on investment':['investment yield','gain from an investment','profitability of an investment'],
  'due diligence':['thorough review','careful examination','detailed assessment'],
  'best practices':['recommended approaches','proven methods','established guidelines'],
  'key performance indicators':['performance measures','metrics for tracking success','crucial measurements'],
  'market dynamics':['market forces','shifts in the market','how the market behaves'],
  'competitive advantage':['edge over competitors','strategic superiority','market advantage'],
  'value proposition':['value offering','core benefit','what is being offered'],
  'quality assurance':['quality control','quality management','standards enforcement'],
  'critical thinking':['analytical reasoning','careful analysis','thoughtful evaluation'],
  'in the field of education':['in education','within the educational sector','across educational settings'],
  'student engagement':['learner involvement','student participation','active learning'],
  'learning outcomes':['educational results','what students learn','learning achievements'],
  'academic performance':['scholarly achievement','grades and test results','educational performance'],
  'pedagogical approach':['teaching method','instructional approach','educational strategy'],
  'policy implications':['effects on policy','consequences for regulation','what this means for policymakers'],
  'policy recommendations':['suggested policies','recommended courses of action','guidance for policymakers'],
  'regulatory framework':['set of rules','the governing regulations','the body of regulations'],
  'legal framework':['the system of laws','the legal structure','the body of law'],
  'moral obligation':['ethical duty','moral duty','an obligation rooted in ethics'],
  'ethical considerations':['moral factors','questions of ethics','ethical concerns'],
  'social responsibility':['duty to society','responsibility toward the community','accountability to the public'],
  'cultural diversity':['variety of cultures','cultural differences','multicultural representation'],
  'systemic issues':['structural problems','issues built into the system','deeply rooted problems'],
  'systemic barriers':['structural obstacles','institutional hurdles','built-in obstacles'],
  'gender equality':['equality between genders','equal treatment regardless of gender','gender parity'],
  'power dynamics':['power relationships','how power is distributed','the balance of power'],
  'climate change':['shifts in climate patterns','global warming','changes in the climate'],
  'environmental sustainability':['ecological balance','long-term environmental health','environmental well-being'],
  'biodiversity loss':['decline in species variety','shrinking biological diversity','loss of plant and animal variety'],
  // 'food security' — kept as-is to prevent cascading synonym garble
  'water scarcity':['shortage of water','limited water availability','insufficient water supply'],
  'urban planning':['city planning','planning how cities grow','designing urban spaces'],
  'technological advancement':['progress in technology','growth of technology','innovation in tools and systems'],
  'technological advancements':['advances in technology','improvements in tools and systems','growth in technical capability'],
  'data-driven':['guided by data','informed by data','based on recorded evidence'],
  'data-driven decision making':['decisions guided by data','using data to inform choices','evidence-based decision making'],
  'cost-effective':['affordable','economical','good value for money','budget-friendly'],
  'labor market':['job market','employment landscape','workforce conditions'],
  'workforce development':['training and skill building','developing worker capability','building human capital'],
  'human capital':['worker skills and knowledge','the value of trained people','the skill base of the labor force'],
  'per capita':['per person','for each individual','on an individual basis'],
  'per annum':['per year','each year','annually'],
  'in the foreseeable future':['in the near future','over the coming years','looking ahead'],
  'in the near future':['soon','before long','in the coming period'],
  'moving forward':['going ahead','from here on','looking ahead'],
  'going forward':['from this point','in the future','from now on'],
  'given the current situation':['under present conditions','as things stand now','in view of current circumstances'],
  'under these circumstances':['given this situation','in light of these conditions','faced with these realities'],
  'it can be seen that':['what becomes apparent is that','the observation here is that','a closer look reveals that'],
  'it is well established that':['there is strong evidence that','research has consistently shown that','the record makes clear that'],
  'it is well documented that':['the record shows clearly that','it is widely recorded that','there is extensive documentation showing that'],
  'it is noteworthy that':['what stands out is that','a point worth noting is that','interestingly'],
  'it is interesting to note that':['one curious finding is that','what catches attention is that','a remarkable point is that'],
  'it is a well-known fact that':['it is widely understood that','as most people know','common knowledge holds that'],
  'with this in mind':['considering this','keeping this in perspective','bearing this in mind'],
  'in particular':['especially','most notably','above all','to single out one case'],
  'as a matter of fact':['in reality','actually','the truth is','in point of fact'],
  'by the same token':['equally','in the same way','following the same logic'],
  'to put it simply':['in simple terms','to break it down','stated plainly'],
  'to put it differently':['said another way','in other words','rephrased'],
  'in other words':['to put it another way','said differently','that is to say'],
  'that is to say':['meaning','in other words','put another way'],
  'notwithstanding':['despite','in spite of','regardless','even with'],
  'inasmuch as':['since','because','given that','to the extent that'],
  'insofar as':['to the extent that','so far as','as far as','regarding the degree to which'],
  'vis-a-vis':['compared to','in relation to','regarding','with respect to'],
  'per se':['by itself','in itself','as such','on its own'],
};


// ═══════════════════════════════════════════════════════════════════
// EXTRA_SYN — 100+ AI signature word replacements
// Merged into engine's SYN dictionary at load time
// ═══════════════════════════════════════════════════════════════════

export const EXTRA_SYN = {
  'delve':['explore','look into','examine','dig into'],
  'underscore':['highlight','stress','emphasize','point to'],
  'pivotal':['central','key','critical','important'],
  'multifaceted':['complex','many-sided','layered'],
  'nuanced':['subtle','detailed','careful'],
  'intricate':['complex','detailed','involved'],
  'encompass':['include','cover','involve'],
  'facilitate':['help with','support','make easier','enable'],
  'paradigm':['model','framework','approach'],
  'leverage':['use','draw on','make use of'],
  'robust':['strong','solid','reliable'],
  'comprehensive':['thorough','complete','broad'],
  'holistic':['overall','complete','whole'],
  'streamline':['simplify','improve','speed up'],
  'foster':['encourage','support','promote'],
  'cultivate':['develop','grow','build'],
  'navigate':['work through','manage','handle'],
  'potential':['potential'],
  'landscape':['environment','scene','setting'],
  'realm':['area','field','domain'],
  'interplay':['interaction','relationship','exchange'],
  'overarching':['overall','broad','general'],
  'underpinning':['supporting','underlying','foundational'],
  'underscoring':['highlighting','stressing','pointing to'],
  'spearheading':['leading','driving','heading'],
  'bolstering':['strengthening','supporting','boosting'],
  'augmenting':['increasing','adding to','expanding'],
  'ameliorating':['improving','easing','helping'],
  'exacerbating':['worsening','intensifying','aggravating'],
  'delineating':['outlining','describing','defining'],
  'elucidating':['explaining','clarifying','making clear'],
  'demystifying':['explaining','clearing up','simplifying'],
  'showcasing':['showing','displaying','presenting'],
  'tapestry':['fabric','picture','mix','collection'],
  'testament':['proof','evidence','sign','reflection'],
  'commendable':['praiseworthy','admirable','notable'],
  'meticulous':['careful','thorough','precise'],
  'meticulously':['carefully','thoroughly','with great care'],
  'groundbreaking':['pioneering','innovative','new'],
  'noteworthy':['notable','worth mentioning','significant'],
  'indispensable':['essential','necessary','critical'],
  'adept':['skilled','capable','proficient'],
  'endeavor':['effort','attempt','pursuit'],
  'endeavors':['efforts','attempts','pursuits'],
  'endeavoring':['trying','working','attempting'],
  'embark':['start','begin','set out'],
  'embarking':['starting','beginning','setting out'],
  'embarks':['starts','begins','sets out'],
  'commencing':['beginning','starting','opening'],
  'culminating':['ending in','resulting in','leading to'],
  'burgeoning':['growing','expanding','rising'],
  'harnessing':['using','putting to work','tapping into'],
  'harness':['use','put to work','tap into'],
  'synergize':['work together','combine','cooperate'],
  'synergizing':['working together','combining','cooperating'],
  'juxtaposition':['contrast','comparison','side-by-side view'],
  'juxtapose':['compare','place side by side','contrast'],
  'quintessential':['classic','typical','ideal'],
  'amidst':['amid','during','in the middle of'],
  'whilst':['while','as','during'],
  'utilise':['use','apply','employ'],
  'utilising':['using','applying','employing'],
  'plethora':['many','a wealth of','a wide range of'],
  'myriad':['many','numerous','a variety of'],
  'paramount':['most important','top priority','above all'],
  'profound':['deep','far-reaching','strong'],
  'profoundly':['deeply','significantly','strongly'],
  'indubitably':['without doubt','certainly','clearly'],
  'unequivocally':['without doubt','clearly','absolutely'],
  'irrefutably':['undeniably','beyond question','without dispute'],
  'incontrovertibly':['undeniably','beyond doubt','certainly'],
  'discernible':['noticeable','visible','clear'],
  'discernibly':['noticeably','visibly','clearly'],
  'tantamount':['equivalent','the same as','equal to'],
  'propitious':['favorable','promising','encouraging'],
  'salient':['important','key','notable'],
  'inadvertently':['accidentally','by mistake','unintentionally'],
  'notwithstanding':['despite','in spite of','regardless of'],
  'pertaining to':['about','related to','concerning'],
  'juxtaposed':['compared','placed side by side','contrasted'],
  'concomitant':['accompanying','associated','linked'],
  'necessitate':['require','call for','demand'],
  'necessitates':['requires','calls for','demands'],
  'predicated':['based','founded','grounded'],
  'constitutes':['makes up','forms','represents'],
  'commenced':['began','started','opened'],
  'delineate':['outline','describe','define'],
  'delineates':['outlines','describes','defines'],
  'elucidate':['explain','clarify','make clear'],
  'elucidates':['explains','clarifies','makes clear'],
  'promulgate':['announce','spread','make known'],
  'promulgates':['announces','spreads','makes known'],
  'perpetuate':['continue','keep alive','maintain'],
  'perpetuates':['continues','keeps alive','maintains'],
  'attenuate':['reduce','lessen','weaken'],
  'attenuates':['reduces','lessens','weakens'],
  'accentuate':['highlight','emphasize','bring out'],
  'accentuates':['highlights','emphasizes','brings out'],
};


// ═══════════════════════════════════════════════════════════════════
// EXTRA_TRANSITIONS — Additional AI phrases to kill
// Merged into engine's PHRASE_KILL at load time
// ═══════════════════════════════════════════════════════════════════

export const EXTRA_TRANSITIONS = {
  // Crazy AI phrases → replacements
  'at the end of the day':['ultimately','when everything is considered','in the final analysis'],
  'it goes without saying':['naturally','of course','clearly'],
  'tip of the iceberg':['only a small part','just the beginning','a fraction of the whole'],
  'food for thought':['something to consider','worth reflecting on','a point to ponder'],
  'game changer':['major shift','significant development','turning point'],
  'circle back':['return to','revisit','come back to'],
  'move the needle':['make a difference','create impact','shift the balance'],
  'deep dive':['detailed look','thorough examination','close analysis'],
  'low-hanging fruit':['easy wins','obvious targets','simple improvements'],
  'in a nutshell':['briefly','in short','to put it simply'],
  'thinking outside the box':['being creative','taking a fresh approach','trying something new'],
  'on the same page':['in agreement','aligned','seeing things the same way'],
  'take it to the next level':['improve further','build on this','push beyond current limits'],
  'pushing the envelope':['testing limits','going beyond norms','breaking new ground'],
  'double-edged sword':['mixed blessing','two-sided issue','something with both positives and negatives'],
  'slippery slope':['risky path','dangerous precedent','gradual escalation'],
  'elephant in the room':['obvious but ignored issue','unspoken problem','the thing nobody mentions'],
  'symphony of':['combination of','blend of','mix of'],
  'dance between':['balance between','tension between','interplay of'],
  'weave together':['combine','bring together','integrate'],
  'fabric of':['structure of','foundation of','makeup of'],
  'beacon of':['symbol of','sign of','example of'],
  'uncharted territory':['new ground','unexplored area','unfamiliar space'],
  // Additional AI-flagged transition patterns
  'henceforth':['from now on','going ahead','after this'],
  'thereby':['in doing so','by this means','because of that'],
  'therein':['in that','in this','within it'],
  'thereof':['of that','of it','from that'],
  'it is no secret that':['everyone knows that','it is well known that','clearly'],
  'it is undeniable that':['no one can dispute that','without question','clearly'],
  'it is paramount that':['it is critical that','the top priority is that','above all'],
  'it bears mentioning that':['worth noting','it should be noted that'],
  'it can be posited that':['one could argue that','a case can be made that'],
  'it can be inferred that':['one can reasonably conclude that','the data points to'],
  'it stands to reason that':['logically','it makes sense that','one would expect that'],
  'there exists a compelling argument':['a strong case can be made','there is good reason to think'],
  'in the contemporary landscape':['in the current setting','today','as things stand now'],
  'in the current paradigm':['in the current model','under present conditions','as things work now'],
  'within this framework':['in this context','under this approach','given this structure'],
};


// ═══════════════════════════════════════════════════════════════════
// EXTRA_COLLOCATIONS — Additional natural word pairings
// ═══════════════════════════════════════════════════════════════════

export const EXTRA_COLLOCATIONS = {};


// ═══════════════════════════════════════════════════════════════════
// PROTECTED_TERMS — Domain terms that must never be swapped
// ═══════════════════════════════════════════════════════════════════

export const PROTECTED_TERMS = [];


// ═══════════════════════════════════════════════════════════════════
// NATURAL_PAIRS — Adjective-noun validation pairs
// ═══════════════════════════════════════════════════════════════════

export const NATURAL_PAIRS = {};
