export interface ConfusionEntry {
  correct: string;
  context: 'always' | 'before_verb' | 'before_noun' | 'comparison' | 'noun' | 'verb' |
    'conjunction' | 'adjective' | 'noun_abstract' | 'praise' | 'complete' | 'writing' | 'still';
  message: string;
}

export const CONFUSION_PAIRS: Record<string, ConfusionEntry> = {
  // Always-wrong misspellings
  'alot':        { correct: 'a lot',       context: 'always', message: '"alot" should be "a lot".' },
  'definately':  { correct: 'definitely',  context: 'always', message: 'Misspelling: "definitely".' },
  'seperate':    { correct: 'separate',    context: 'always', message: 'Misspelling: "separate".' },
  'occured':     { correct: 'occurred',    context: 'always', message: 'Misspelling: "occurred".' },
  'recieve':     { correct: 'receive',     context: 'always', message: 'Misspelling: "receive".' },
  'acheive':     { correct: 'achieve',     context: 'always', message: 'Misspelling: "achieve".' },
  'accomodate':  { correct: 'accommodate', context: 'always', message: 'Misspelling: "accommodate".' },
  'occurence':   { correct: 'occurrence',  context: 'always', message: 'Misspelling: "occurrence".' },
  'neccessary':  { correct: 'necessary',   context: 'always', message: 'Misspelling: "necessary".' },
  'untill':      { correct: 'until',       context: 'always', message: 'Misspelling: "until".' },
  'begining':    { correct: 'beginning',   context: 'always', message: 'Misspelling: "beginning".' },
  'writting':    { correct: 'writing',     context: 'always', message: 'Misspelling: "writing".' },
  'beleive':     { correct: 'believe',     context: 'always', message: 'Misspelling: "believe".' },
  'arguement':   { correct: 'argument',    context: 'always', message: 'Misspelling: "argument".' },
  'tommorow':    { correct: 'tomorrow',    context: 'always', message: 'Misspelling: "tomorrow".' },
  'goverment':   { correct: 'government',  context: 'always', message: 'Misspelling: "government".' },
  'enviroment':  { correct: 'environment', context: 'always', message: 'Misspelling: "environment".' },
  'independant': { correct: 'independent', context: 'always', message: 'Misspelling: "independent".' },
  'wierd':       { correct: 'weird',       context: 'always', message: 'Misspelling: "weird".' },
  'priviledge':  { correct: 'privilege',   context: 'always', message: 'Misspelling: "privilege".' },
  'concious':    { correct: 'conscious',   context: 'always', message: 'Misspelling: "conscious".' },
  'succesful':   { correct: 'successful',  context: 'always', message: 'Misspelling: "successful".' },
  'thier':       { correct: 'their',       context: 'always', message: 'Misspelling: "their".' },
  'teh':         { correct: 'the',         context: 'always', message: 'Misspelling: "the".' },
  'hte':         { correct: 'the',         context: 'always', message: 'Misspelling: "the".' },
  'adn':         { correct: 'and',         context: 'always', message: 'Misspelling: "and".' },
  'doesnt':      { correct: "doesn't",     context: 'always', message: 'Missing apostrophe: "doesn\'t".' },
  'dont':        { correct: "don't",       context: 'always', message: 'Missing apostrophe: "don\'t".' },
  'cant':        { correct: "can't",       context: 'always', message: 'Missing apostrophe: "can\'t".' },
  'wont':        { correct: "won't",       context: 'always', message: 'Missing apostrophe: "won\'t".' },
  'isnt':        { correct: "isn't",       context: 'always', message: 'Missing apostrophe: "isn\'t".' },
  'wasnt':       { correct: "wasn't",      context: 'always', message: 'Missing apostrophe: "wasn\'t".' },
  'arent':       { correct: "aren't",      context: 'always', message: 'Missing apostrophe: "aren\'t".' },
  'werent':      { correct: "weren't",     context: 'always', message: 'Missing apostrophe: "weren\'t".' },
  'havent':      { correct: "haven't",     context: 'always', message: 'Missing apostrophe: "haven\'t".' },
  'hasnt':       { correct: "hasn't",      context: 'always', message: 'Missing apostrophe: "hasn\'t".' },
  'didnt':       { correct: "didn't",      context: 'always', message: 'Missing apostrophe: "didn\'t".' },
  'shouldnt':    { correct: "shouldn't",   context: 'always', message: 'Missing apostrophe: "shouldn\'t".' },
  'couldnt':     { correct: "couldn't",    context: 'always', message: 'Missing apostrophe: "couldn\'t".' },
  'wouldnt':     { correct: "wouldn't",    context: 'always', message: 'Missing apostrophe: "wouldn\'t".' },
  'im':          { correct: "I'm",         context: 'always', message: 'Missing apostrophe: "I\'m".' },
  'ive':         { correct: "I've",        context: 'always', message: 'Missing apostrophe: "I\'ve".' },
  'youre':       { correct: "you're",      context: 'always', message: 'Missing apostrophe: "you\'re".' },
  'theyre':      { correct: "they're",     context: 'always', message: 'Missing apostrophe: "they\'re".' },
  'hes':         { correct: "he's",        context: 'always', message: 'Missing apostrophe: "he\'s".' },
  'shes':        { correct: "she's",       context: 'always', message: 'Missing apostrophe: "she\'s".' },

  // Context-dependent confusion pairs
  'its':         { correct: "it's",       context: 'before_verb', message: 'Did you mean "it\'s" (it is)?' },
  "it's":        { correct: 'its',        context: 'before_noun', message: 'Did you mean "its" (possessive)?' },
  'your':        { correct: "you're",     context: 'before_verb', message: 'Did you mean "you\'re" (you are)?' },
  "you're":      { correct: 'your',       context: 'before_noun', message: 'Did you mean "your" (possessive)?' },
  'their':       { correct: "they're",    context: 'before_verb', message: 'Did you mean "they\'re" (they are)?' },
  "they're":     { correct: 'their',      context: 'before_noun', message: 'Did you mean "their" (possessive)?' },
  'there':       { correct: 'their',      context: 'before_noun', message: 'Did you mean "their" (possessive)?' },
  'then':        { correct: 'than',       context: 'comparison',  message: 'Did you mean "than" (comparison)?' },
  'affect':      { correct: 'effect',     context: 'noun',        message: 'Did you mean "effect" (noun)?' },
  'effect':      { correct: 'affect',     context: 'verb',        message: 'Did you mean "affect" (verb)?' },
  'loose':       { correct: 'lose',       context: 'verb',        message: 'Did you mean "lose" (to misplace)?' },
  'weather':     { correct: 'whether',    context: 'conjunction', message: 'Did you mean "whether" (if)?' },
  'principle':   { correct: 'principal',  context: 'adjective',   message: 'Did you mean "principal" (main/head)?' },
  'principal':   { correct: 'principle',  context: 'noun_abstract', message: 'Did you mean "principle" (rule/belief)?' },
  'complement':  { correct: 'compliment', context: 'praise',      message: 'Did you mean "compliment" (praise)?' },
  'compliment':  { correct: 'complement', context: 'complete',    message: 'Did you mean "complement" (go with)?' },
  'stationary':  { correct: 'stationery', context: 'writing',     message: 'Did you mean "stationery" (paper/pens)?' },
  'stationery':  { correct: 'stationary', context: 'still',       message: 'Did you mean "stationary" (not moving)?' },
};
