export { ABBREVIATIONS, PRONOUNS, SINGULAR_PRONOUNS, PLURAL_PRONOUNS, FIRST_PERSON_SINGULAR,
  AUXILIARIES, MODALS, PREPOSITIONS, CONJUNCTIONS, DETERMINERS, UNCOUNTABLE_NOUNS,
  TRANSITION_WORDS, VOWELS, VOWEL_SOUND_EXCEPTIONS, CONSONANT_SOUND_EXCEPTIONS,
} from './dictionary';
export { CONTRACTIONS } from './contractions';
export { CONFUSION_PAIRS, type ConfusionEntry } from './confusionSets';
export { IRREGULAR_VERBS, FORM_TO_BASE } from './irregularVerbs';
