export const IRREGULAR_VERBS: Record<string, { past: string; pp: string; third: string }> = {
  be:     { past: 'was',       pp: 'been',       third: 'is' },
  have:   { past: 'had',       pp: 'had',        third: 'has' },
  do:     { past: 'did',       pp: 'done',       third: 'does' },
  go:     { past: 'went',      pp: 'gone',       third: 'goes' },
  get:    { past: 'got',       pp: 'gotten',     third: 'gets' },
  make:   { past: 'made',      pp: 'made',       third: 'makes' },
  take:   { past: 'took',      pp: 'taken',      third: 'takes' },
  come:   { past: 'came',      pp: 'come',       third: 'comes' },
  see:    { past: 'saw',       pp: 'seen',       third: 'sees' },
  know:   { past: 'knew',      pp: 'known',      third: 'knows' },
  give:   { past: 'gave',      pp: 'given',      third: 'gives' },
  find:   { past: 'found',     pp: 'found',      third: 'finds' },
  think:  { past: 'thought',   pp: 'thought',    third: 'thinks' },
  tell:   { past: 'told',      pp: 'told',       third: 'tells' },
  say:    { past: 'said',      pp: 'said',       third: 'says' },
  buy:    { past: 'bought',    pp: 'bought',     third: 'buys' },
  bring:  { past: 'brought',   pp: 'brought',    third: 'brings' },
  write:  { past: 'wrote',     pp: 'written',    third: 'writes' },
  read:   { past: 'read',      pp: 'read',       third: 'reads' },
  run:    { past: 'ran',       pp: 'run',        third: 'runs' },
  eat:    { past: 'ate',       pp: 'eaten',      third: 'eats' },
  drink:  { past: 'drank',     pp: 'drunk',      third: 'drinks' },
  sleep:  { past: 'slept',     pp: 'slept',      third: 'sleeps' },
  sit:    { past: 'sat',       pp: 'sat',        third: 'sits' },
  stand:  { past: 'stood',     pp: 'stood',      third: 'stands' },
  speak:  { past: 'spoke',     pp: 'spoken',     third: 'speaks' },
  meet:   { past: 'met',       pp: 'met',        third: 'meets' },
  leave:  { past: 'left',      pp: 'left',       third: 'leaves' },
  put:    { past: 'put',       pp: 'put',        third: 'puts' },
  show:   { past: 'showed',    pp: 'shown',      third: 'shows' },
  feel:   { past: 'felt',      pp: 'felt',       third: 'feels' },
  keep:   { past: 'kept',      pp: 'kept',       third: 'keeps' },
  begin:  { past: 'began',     pp: 'begun',      third: 'begins' },
  forget: { past: 'forgot',    pp: 'forgotten',  third: 'forgets' },
  choose: { past: 'chose',     pp: 'chosen',     third: 'chooses' },
  break:  { past: 'broke',     pp: 'broken',     third: 'breaks' },
  win:    { past: 'won',       pp: 'won',        third: 'wins' },
  send:   { past: 'sent',      pp: 'sent',       third: 'sends' },
  pay:    { past: 'paid',      pp: 'paid',       third: 'pays' },
  sell:   { past: 'sold',      pp: 'sold',       third: 'sells' },
  cut:    { past: 'cut',       pp: 'cut',        third: 'cuts' },
  fly:    { past: 'flew',      pp: 'flown',      third: 'flies' },
  fall:   { past: 'fell',      pp: 'fallen',     third: 'falls' },
  grow:   { past: 'grew',      pp: 'grown',      third: 'grows' },
  draw:   { past: 'drew',      pp: 'drawn',      third: 'draws' },
  drive:  { past: 'drove',     pp: 'driven',     third: 'drives' },
  ride:   { past: 'rode',      pp: 'ridden',     third: 'rides' },
  sing:   { past: 'sang',      pp: 'sung',       third: 'sings' },
  swim:   { past: 'swam',      pp: 'swum',       third: 'swims' },
  teach:  { past: 'taught',    pp: 'taught',     third: 'teaches' },
  catch:  { past: 'caught',    pp: 'caught',     third: 'catches' },
  build:  { past: 'built',     pp: 'built',      third: 'builds' },
  hear:   { past: 'heard',     pp: 'heard',      third: 'hears' },
  hold:   { past: 'held',      pp: 'held',       third: 'holds' },
  lead:   { past: 'led',       pp: 'led',        third: 'leads' },
  lose:   { past: 'lost',      pp: 'lost',       third: 'loses' },
  mean:   { past: 'meant',     pp: 'meant',      third: 'means' },
  spend:  { past: 'spent',     pp: 'spent',      third: 'spends' },
  understand: { past: 'understood', pp: 'understood', third: 'understands' },
  set:    { past: 'set',       pp: 'set',        third: 'sets' },
  let:    { past: 'let',       pp: 'let',        third: 'lets' },
  hang:   { past: 'hung',      pp: 'hung',       third: 'hangs' },
  lay:    { past: 'laid',      pp: 'laid',       third: 'lays' },
  lie:    { past: 'lay',       pp: 'lain',       third: 'lies' },
  rise:   { past: 'rose',      pp: 'risen',      third: 'rises' },
  wear:   { past: 'wore',      pp: 'worn',       third: 'wears' },
  hide:   { past: 'hid',       pp: 'hidden',     third: 'hides' },
  bite:   { past: 'bit',       pp: 'bitten',     third: 'bites' },
  tear:   { past: 'tore',      pp: 'torn',       third: 'tears' },
  shake:  { past: 'shook',     pp: 'shaken',     third: 'shakes' },
  steal:  { past: 'stole',     pp: 'stolen',     third: 'steals' },
  strike: { past: 'struck',    pp: 'struck',     third: 'strikes' },
  throw:  { past: 'threw',     pp: 'thrown',     third: 'throws' },
  wake:   { past: 'woke',      pp: 'woken',      third: 'wakes' },
  freeze: { past: 'froze',     pp: 'frozen',     third: 'freezes' },
  swear:  { past: 'swore',     pp: 'sworn',      third: 'swears' },
};

/**
 * Reverse lookup: map any form to its base (infinitive).
 */
export const FORM_TO_BASE = new Map<string, string>();
for (const [base, forms] of Object.entries(IRREGULAR_VERBS)) {
  FORM_TO_BASE.set(base, base);
  FORM_TO_BASE.set(forms.past, base);
  FORM_TO_BASE.set(forms.pp, base);
  FORM_TO_BASE.set(forms.third, base);
}
